-- ==========================================================================
-- Baseline Seed Data — auto-generated by db/scripts/consolidate.mjs
-- Generated: 2026-02-13T14:56:53.998Z
-- ==========================================================================

-- checklist_modelos
--
-- PostgreSQL database dump
--

\restrict 3yh6SqI80kwcHER0jhNNWlW1QXGieaLYtp4NtpPbSyfCbEL2pgdcjprMHNAe9Ts

-- Dumped from database version 15.15
-- Dumped by pg_dump version 15.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: checklist_modelos; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.checklist_modelos VALUES ('d3709ef4-96f2-46ef-b531-e12c00ae5354', 'RECEBIMENTO', 'IDENTIFICACAO_GED', 'Identificação oficial do processo por ID GED validada', true, 1, true, '2026-02-10 18:29:34.755898+00', '2026-02-10 18:29:34.755898+00');
INSERT INTO public.checklist_modelos VALUES ('64ff5bfe-5c67-469f-a611-380c122da5e2', 'RECEBIMENTO', 'CONFERENCIA_ORGAO_PROJETO', 'Conferência de órgão e projeto realizada', true, 2, true, '2026-02-10 18:29:34.755898+00', '2026-02-10 18:29:34.755898+00');
INSERT INTO public.checklist_modelos VALUES ('95e490f5-cae0-41fd-9448-8468f1bfa2b3', 'RECEBIMENTO', 'CONFERENCIA_INTEGRIDADE', 'Conferência física inicial de integridade concluída', true, 3, true, '2026-02-10 18:29:34.755898+00', '2026-02-10 18:29:34.755898+00');
INSERT INTO public.checklist_modelos VALUES ('43e4c011-d866-4bc0-bce6-1fd0b8a62db8', 'RECEBIMENTO', 'COMPROVANTE_RECEBIMENTO', 'Comprovante de recebimento emitido e vinculado', true, 5, true, '2026-02-10 18:29:34.755898+00', '2026-02-10 18:29:34.755898+00');
INSERT INTO public.checklist_modelos VALUES ('a4915939-f117-4a04-bcfd-7055eb8433ea', 'PREPARACAO', 'RETIRADA_ARMARIO', 'Retirada do armário registrada para preparação', true, 1, true, '2026-02-10 18:29:34.755898+00', '2026-02-10 18:29:34.755898+00');
INSERT INTO public.checklist_modelos VALUES ('0ae1e346-422f-4744-847b-b8b38fef72c8', 'PREPARACAO', 'HIGIENIZACAO', 'Higienização documental concluída', true, 2, true, '2026-02-10 18:29:34.755898+00', '2026-02-10 18:29:34.755898+00');
INSERT INTO public.checklist_modelos VALUES ('301c7f91-e1e4-47f8-8cbc-5c149f5abb5d', 'PREPARACAO', 'ORDENACAO_DOCUMENTAL', 'Ordenação documental validada', true, 3, true, '2026-02-10 18:29:34.755898+00', '2026-02-10 18:29:34.755898+00');
INSERT INTO public.checklist_modelos VALUES ('42566f57-9efc-40da-80b9-e03f03de1cf7', 'PREPARACAO', 'SINALIZACAO_FRAGILIDADES', 'Fragilidades e exceções sinalizadas', true, 4, true, '2026-02-10 18:29:34.755898+00', '2026-02-10 18:29:34.755898+00');
INSERT INTO public.checklist_modelos VALUES ('b2e72509-f88e-489b-945b-1b23b46f4faf', 'PREPARACAO', 'DEVOLUCAO_ARMARIO', 'Devolução ao armário de digitalização registrada', true, 5, true, '2026-02-10 18:29:34.755898+00', '2026-02-10 18:29:34.755898+00');
INSERT INTO public.checklist_modelos VALUES ('6791e9a4-ca0c-409e-9abd-1d4be2f96065', 'DIGITALIZACAO', 'RETIRADA_ARMARIO', 'Retirada do armário registrada para digitalização', true, 1, true, '2026-02-10 18:29:34.755898+00', '2026-02-10 18:29:34.755898+00');
INSERT INTO public.checklist_modelos VALUES ('79e6bea5-29a7-433f-8ea3-c330d3e1d124', 'DIGITALIZACAO', 'CALIBRACAO_EQUIPAMENTO', 'Calibração e perfil técnico do scanner conferidos', true, 2, true, '2026-02-10 18:29:34.755898+00', '2026-02-10 18:29:34.755898+00');
INSERT INTO public.checklist_modelos VALUES ('8270170f-6430-4fe5-81e0-eecb8b38874c', 'DIGITALIZACAO', 'MARCACAO_FORMATOS', 'Marcação de P/B, colorido e A3 registrada', true, 3, true, '2026-02-10 18:29:34.755898+00', '2026-02-10 18:29:34.755898+00');
INSERT INTO public.checklist_modelos VALUES ('e862321b-1e86-473c-a101-f1193b5cfb76', 'DIGITALIZACAO', 'ENVIO_SEADESK', 'Envio via Seadesk confirmado', true, 4, true, '2026-02-10 18:29:34.755898+00', '2026-02-10 18:29:34.755898+00');
INSERT INTO public.checklist_modelos VALUES ('3c19725c-53f2-4009-9045-351111dfc1d9', 'DIGITALIZACAO', 'DEVOLUCAO_ARMARIO', 'Devolução ao armário de conferência registrada', true, 5, true, '2026-02-10 18:29:34.755898+00', '2026-02-10 18:29:34.755898+00');
INSERT INTO public.checklist_modelos VALUES ('4d8d215a-910c-4b6e-af34-c8d928967382', 'CONFERENCIA', 'RETIRADA_ARMARIO', 'Retirada do armário registrada para conferência', true, 1, true, '2026-02-10 18:29:34.755898+00', '2026-02-10 18:29:34.755898+00');
INSERT INTO public.checklist_modelos VALUES ('a6e339dc-37da-4375-a29c-4606a1302c77', 'CONFERENCIA', 'VALIDACAO_GED', 'Validação no GED de paginação, ordem e indexação concluída', true, 2, true, '2026-02-10 18:29:34.755898+00', '2026-02-10 18:29:34.755898+00');
INSERT INTO public.checklist_modelos VALUES ('c8800ef6-a104-4c4f-9d44-321f92de0305', 'CONFERENCIA', 'TRATATIVA_EXCECOES', 'Tratativa de mídias e coloridos concluída', true, 3, true, '2026-02-10 18:29:34.755898+00', '2026-02-10 18:29:34.755898+00');
INSERT INTO public.checklist_modelos VALUES ('10d0e0a1-02f7-4433-a887-b3b8d9075531', 'CONFERENCIA', 'CHECKLIST_CRITICO', 'Checklist crítico de conferência concluído', true, 4, true, '2026-02-10 18:29:34.755898+00', '2026-02-10 18:29:34.755898+00');
INSERT INTO public.checklist_modelos VALUES ('55205645-ab0e-427c-8a74-327ee0b354e2', 'CONFERENCIA', 'DEVOLUCAO_ARMARIO', 'Devolução ao armário de montagem registrada', true, 5, true, '2026-02-10 18:29:34.755898+00', '2026-02-10 18:29:34.755898+00');
INSERT INTO public.checklist_modelos VALUES ('b10067e8-26d6-4414-bf74-65df536a56e9', 'MONTAGEM', 'RETIRADA_ARMARIO', 'Retirada do armário registrada para montagem', true, 1, true, '2026-02-10 18:29:34.755898+00', '2026-02-10 18:29:34.755898+00');
INSERT INTO public.checklist_modelos VALUES ('0e30366e-287c-4d33-8fb1-d0a677326cd6', 'MONTAGEM', 'RECOMPOSICAO_FISICA', 'Checklist de recomposição física concluído', true, 2, true, '2026-02-10 18:29:34.755898+00', '2026-02-10 18:29:34.755898+00');
INSERT INTO public.checklist_modelos VALUES ('2a4526a1-ba7d-466d-8395-d42cf49f3e8a', 'MONTAGEM', 'PREPARACAO_DEVOLUCAO', 'Preparação para devolução final concluída', true, 3, true, '2026-02-10 18:29:34.755898+00', '2026-02-10 18:29:34.755898+00');
INSERT INTO public.checklist_modelos VALUES ('049859d2-1b9f-4ed5-98fc-9c7fa7233d87', 'MONTAGEM', 'DEVOLUCAO_ARMARIO', 'Devolução ao armário de CQ registrada', true, 4, true, '2026-02-10 18:29:34.755898+00', '2026-02-10 18:29:34.755898+00');
INSERT INTO public.checklist_modelos VALUES ('6260a193-50f6-4adc-8a57-0f5387251d23', 'CONTROLE_QUALIDADE', 'SELECAO_LOTE_10', 'Lote de 10 repositórios selecionado', true, 1, true, '2026-02-10 18:29:34.755898+00', '2026-02-10 18:29:34.755898+00');
INSERT INTO public.checklist_modelos VALUES ('bbd39e92-8003-473f-906d-000665244822', 'CONTROLE_QUALIDADE', 'AUDITORIA_CRUZADA', 'Auditoria físico x GED x recebimento concluída', true, 2, true, '2026-02-10 18:29:34.755898+00', '2026-02-10 18:29:34.755898+00');
INSERT INTO public.checklist_modelos VALUES ('e807028b-0aee-4e88-9c99-0ce5f75e7165', 'CONTROLE_QUALIDADE', 'RESULTADO_REGISTRADO', 'Aprovação/reprovação registrada por repositório', true, 3, true, '2026-02-10 18:29:34.755898+00', '2026-02-10 18:29:34.755898+00');
INSERT INTO public.checklist_modelos VALUES ('ddf418bc-43a7-4308-94d7-38c6cbea879b', 'CONTROLE_QUALIDADE', 'RELATORIO_ENTREGA_GERADO', 'Relatório de entrega PDF gerado', true, 4, true, '2026-02-10 18:29:34.755898+00', '2026-02-10 18:29:34.755898+00');
INSERT INTO public.checklist_modelos VALUES ('630bb308-5f52-43fa-ab7a-02937e2b77c4', 'ENTREGA', 'CONFERENCIA_FINAL', 'Conferência final de integridade do repositório', true, 1, true, '2026-02-11 18:58:36.527904+00', '2026-02-11 18:58:36.527904+00');
INSERT INTO public.checklist_modelos VALUES ('46867ec8-48a4-4661-9043-60ed881066b5', 'ENTREGA', 'REGISTRO_DEVOLUCAO', 'Registro de devolução ao órgão de origem', true, 2, true, '2026-02-11 18:58:36.527904+00', '2026-02-11 18:58:36.527904+00');
INSERT INTO public.checklist_modelos VALUES ('aaf8e4c7-d93d-4278-a3b8-76782bb3e5e3', 'RECEBIMENTO', 'REGISTRO_ARMARIO_INICIAL', 'Armário inicial registrado para o repositório', true, 4, false, '2026-02-10 18:29:34.755898+00', '2026-02-11 19:41:47.295182+00');


--
-- PostgreSQL database dump complete
--

\unrestrict 3yh6SqI80kwcHER0jhNNWlW1QXGieaLYtp4NtpPbSyfCbEL2pgdcjprMHNAe9Ts

-- classificacoes_recebimento
--
-- PostgreSQL database dump
--

\restrict 5dXS57ecKKkgFEJyQjayTdXUn63XmZQfdYfzgVGHoJoU54KhKnoJyQIHjZOTUQ6

-- Dumped from database version 15.15
-- Dumped by pg_dump version 15.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: classificacoes_recebimento; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.classificacoes_recebimento VALUES ('e940405d-1271-4719-881c-de678cafb874', '000 - ADMINISTRAÇÃO GERAL', true, '490d5c6e-02fa-467c-b071-bcb5f85e49e7', '2026-02-12 16:37:10.628837+00');
INSERT INTO public.classificacoes_recebimento VALUES ('236e2903-6ba0-44a5-a420-4cd46ec7f786', '030 - MATERIAL', true, '490d5c6e-02fa-467c-b071-bcb5f85e49e7', '2026-02-12 16:37:10.628837+00');
INSERT INTO public.classificacoes_recebimento VALUES ('abb1bec5-6f8d-4707-bd65-160df1765b2e', '200 - POLÍTICAS RURAIS E DE DEFESA DO MEIO AMBIENTE', true, '490d5c6e-02fa-467c-b071-bcb5f85e49e7', '2026-02-12 16:37:10.628837+00');
INSERT INTO public.classificacoes_recebimento VALUES ('2b61e1d4-4a53-4aa9-bee0-12e9f80f39a9', '250 - DEFESA AMBIENTAL', true, '490d5c6e-02fa-467c-b071-bcb5f85e49e7', '2026-02-12 16:37:10.628837+00');
INSERT INTO public.classificacoes_recebimento VALUES ('c96a783e-2604-4bee-acc4-d6a2a1980de1', '251 - LICENCIAMENTOS AMBIENTAIS', true, '490d5c6e-02fa-467c-b071-bcb5f85e49e7', '2026-02-12 16:37:10.628837+00');
INSERT INTO public.classificacoes_recebimento VALUES ('1a334a65-f926-43d7-8f05-b87d34849be3', '251.1 - Propriedade Rural', true, '490d5c6e-02fa-467c-b071-bcb5f85e49e7', '2026-02-12 16:37:10.628837+00');
INSERT INTO public.classificacoes_recebimento VALUES ('0c02ef1d-e12f-4eb7-95b8-8b5efbf19d03', '251.2 - LICENCIAMENTOS AMBIENTAIS DE INFRA-ESTRUTURA, MINERAÇÃO, INDÚSTRIA E SERVIÇOS', true, '490d5c6e-02fa-467c-b071-bcb5f85e49e7', '2026-02-12 16:37:10.628837+00');
INSERT INTO public.classificacoes_recebimento VALUES ('1e998dab-b641-4cab-9760-17f08730f36c', '251.21 - ATIVIDADES INDUSTRIAIS', true, '490d5c6e-02fa-467c-b071-bcb5f85e49e7', '2026-02-12 16:37:10.628837+00');
INSERT INTO public.classificacoes_recebimento VALUES ('051189ed-6798-4098-80cb-3f571552266a', '251.22 - ATIVIDADES AGROPECUÁRIAS E DE PISCICULTURA', true, '490d5c6e-02fa-467c-b071-bcb5f85e49e7', '2026-02-12 16:37:10.628837+00');
INSERT INTO public.classificacoes_recebimento VALUES ('3505a39f-f2d0-4d08-a785-014b6ad6e211', '251.23 - ATIVIDADES DE EMPREENDIMENTOS ENERGÉTICOS', true, '490d5c6e-02fa-467c-b071-bcb5f85e49e7', '2026-02-12 16:37:10.628837+00');
INSERT INTO public.classificacoes_recebimento VALUES ('f697ea9e-cac5-4e4c-993c-5017c9905e72', '251.23.1 - Distribuição', true, '490d5c6e-02fa-467c-b071-bcb5f85e49e7', '2026-02-12 16:37:10.628837+00');
INSERT INTO public.classificacoes_recebimento VALUES ('7fe717ed-6bf4-4d3b-87c0-9cc3158d6608', '251.23.2 - Geração', true, '490d5c6e-02fa-467c-b071-bcb5f85e49e7', '2026-02-12 16:37:10.628837+00');
INSERT INTO public.classificacoes_recebimento VALUES ('63c73090-da78-4367-9145-dbc7015e23d9', '251.24 - PRESTADORES DE SERVIÇO', true, '490d5c6e-02fa-467c-b071-bcb5f85e49e7', '2026-02-12 16:37:10.628837+00');
INSERT INTO public.classificacoes_recebimento VALUES ('d68d91fe-83a0-40cd-8258-4de7eeac0347', '251.25 - EMPREENDIMENTOS DE BASE FLORESTAL', true, '490d5c6e-02fa-467c-b071-bcb5f85e49e7', '2026-02-12 16:37:10.628837+00');
INSERT INTO public.classificacoes_recebimento VALUES ('773cd1e1-3cd0-4ebf-a2a2-bb7a2800e1c6', '251.26 - EMPRENDIMENTOS DE MINERAÇÃO', true, '490d5c6e-02fa-467c-b071-bcb5f85e49e7', '2026-02-12 16:37:10.628837+00');
INSERT INTO public.classificacoes_recebimento VALUES ('ffa5641a-17ef-4004-bf92-326f57fce9e2', '251.27 - LICENCIAMENTOS DE INFRAESTRUTURA', true, '490d5c6e-02fa-467c-b071-bcb5f85e49e7', '2026-02-12 16:37:10.628837+00');
INSERT INTO public.classificacoes_recebimento VALUES ('9d48a8f9-31fc-44cc-8cf7-9c1926d7d22f', '251.27.1 - ATIVIDADES POTENCIALMENTE POLUIDORAS LIGADAS A RESÍDUOS SÓLIDOS', true, '490d5c6e-02fa-467c-b071-bcb5f85e49e7', '2026-02-12 16:37:10.628837+00');
INSERT INTO public.classificacoes_recebimento VALUES ('3d25c808-ec97-49b5-bc6b-2dcfd53ea27d', '256 - FISCALIZAÇÃO AMBIENTAL', true, '490d5c6e-02fa-467c-b071-bcb5f85e49e7', '2026-02-12 16:37:10.628837+00');


--
-- PostgreSQL database dump complete
--

\unrestrict 5dXS57ecKKkgFEJyQjayTdXUn63XmZQfdYfzgVGHoJoU54KhKnoJyQIHjZOTUQ6

-- schema_migrations
--
-- PostgreSQL database dump
--

\restrict YcgNkOYSlt3NckR8DPSQaGMK841pazG7K1AsIqc8kqo6K0fwcOB4Ng1efHKUx7f

-- Dumped from database version 15.15
-- Dumped by pg_dump version 15.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: schema_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.schema_migrations VALUES ('001_initial_schema', '2026-01-30 16:09:02.599048+00');
INSERT INTO public.schema_migrations VALUES ('002_coordenadorias', '2026-01-30 16:09:02.68296+00');
INSERT INTO public.schema_migrations VALUES ('003_colaboradores', '2026-01-30 16:09:02.719382+00');
INSERT INTO public.schema_migrations VALUES ('004_etapas', '2026-01-30 16:09:02.759145+00');
INSERT INTO public.schema_migrations VALUES ('005_fontes_dados', '2026-01-30 16:09:02.792283+00');
INSERT INTO public.schema_migrations VALUES ('006_processos_principais', '2026-01-30 16:09:02.820829+00');
INSERT INTO public.schema_migrations VALUES ('007_volumes', '2026-01-30 16:09:02.882195+00');
INSERT INTO public.schema_migrations VALUES ('008_apensos', '2026-01-30 16:09:02.927101+00');
INSERT INTO public.schema_migrations VALUES ('009_registros_producao', '2026-01-30 16:09:02.965752+00');
INSERT INTO public.schema_migrations VALUES ('010_documentos_ocr', '2026-01-30 16:09:03.039904+00');
INSERT INTO public.schema_migrations VALUES ('011_importacoes', '2026-01-30 16:09:03.081487+00');
INSERT INTO public.schema_migrations VALUES ('012_auditoria', '2026-01-30 16:09:03.12765+00');
INSERT INTO public.schema_migrations VALUES ('013_categorias', '2026-01-30 16:09:03.174284+00');
INSERT INTO public.schema_migrations VALUES ('014_tags', '2026-01-30 16:09:03.204512+00');
INSERT INTO public.schema_migrations VALUES ('015_artigos', '2026-01-30 16:09:03.225261+00');
INSERT INTO public.schema_migrations VALUES ('016_artigos_tags', '2026-01-30 16:09:03.26856+00');
INSERT INTO public.schema_migrations VALUES ('017_artigos_relacionados', '2026-01-30 16:09:03.288332+00');
INSERT INTO public.schema_migrations VALUES ('020_fontes_dados_api', '2026-01-30 16:09:03.407184+00');
INSERT INTO public.schema_migrations VALUES ('021_fontes_dados_configuracoes', '2026-01-30 16:09:03.415485+00');
INSERT INTO public.schema_migrations VALUES ('022_recebimentos', '2026-01-30 16:09:03.432375+00');
INSERT INTO public.schema_migrations VALUES ('023_glossario', '2026-01-30 16:09:03.469596+00');
INSERT INTO public.schema_migrations VALUES ('025_add_interessado_processos_principais', '2026-01-31 13:53:46.818208+00');
INSERT INTO public.schema_migrations VALUES ('026_add_email_to_colaboradores', '2026-01-31 13:55:27.999572+00');
INSERT INTO public.schema_migrations VALUES ('027_nullable_importacoes_colaborador', '2026-02-02 18:59:38.234562+00');
INSERT INTO public.schema_migrations VALUES ('018_configuracao_empresa', '2026-02-02 19:02:51.48638+00');
INSERT INTO public.schema_migrations VALUES ('019_usuarios', '2026-02-02 19:03:40.027504+00');
INSERT INTO public.schema_migrations VALUES ('024_configuracao_projetos', '2026-02-02 19:03:58.198722+00');
INSERT INTO public.schema_migrations VALUES ('028_registros_importados', '2026-02-03 20:13:54.169513+00');
INSERT INTO public.schema_migrations VALUES ('029_add_importacao_id_to_registros_producao', '2026-02-03 20:13:54.286208+00');
INSERT INTO public.schema_migrations VALUES ('030_update_importacao_fk', '2026-02-04 14:03:32.653226+00');
INSERT INTO public.schema_migrations VALUES ('031_allow_delete_importados', '2026-02-04 14:08:07.017209+00');
INSERT INTO public.schema_migrations VALUES ('032_producao_metas_mapeamentos', '2026-02-10 18:29:34.509071+00');
INSERT INTO public.schema_migrations VALUES ('033_fluxo_operacional_repositorios', '2026-02-10 18:29:34.755898+00');
INSERT INTO public.schema_migrations VALUES ('034_fix_auditoria_operacional', '2026-02-10 18:35:52.223224+00');
INSERT INTO public.schema_migrations VALUES ('035_migrate_supervisor_to_operador', '2026-02-10 18:41:06.024632+00');
INSERT INTO public.schema_migrations VALUES ('036_base_conhecimento_operacional', '2026-02-10 19:04:28.022526+00');
INSERT INTO public.schema_migrations VALUES ('037_recebimento_documentos_ocr', '2026-02-10 20:12:32.452521+00');
INSERT INTO public.schema_migrations VALUES ('038_importacoes_legado_operacional', '2026-02-10 20:19:12.468399+00');
INSERT INTO public.schema_migrations VALUES ('039_drop_orphan_tables', '2026-02-11 16:36:03.736183+00');
INSERT INTO public.schema_migrations VALUES ('042_fix_checklist_conclusao_sem_modelos', '2026-02-11 18:58:36.527904+00');
INSERT INTO public.schema_migrations VALUES ('043_repositorios_data_entrega', '2026-02-11 19:16:08.804992+00');
INSERT INTO public.schema_migrations VALUES ('044_armario_opcional', '2026-02-11 19:20:23.516038+00');
INSERT INTO public.schema_migrations VALUES ('045_desativar_modelo_armario', '2026-02-11 19:41:47.295182+00');
INSERT INTO public.schema_migrations VALUES ('040_seadesk_confirmacao', '2026-02-12 16:15:48.719004+00');
INSERT INTO public.schema_migrations VALUES ('041_usuario_operador_padrao', '2026-02-12 16:15:48.826999+00');
INSERT INTO public.schema_migrations VALUES ('046_add_digitalizacao_colorida', '2026-02-12 16:15:48.91208+00');
INSERT INTO public.schema_migrations VALUES ('047_recebimento_novo_modelo', '2026-02-12 16:15:48.919496+00');
INSERT INTO public.schema_migrations VALUES ('048_recebimento_setor_classificacao', '2026-02-12 16:31:57.06613+00');
INSERT INTO public.schema_migrations VALUES ('049_seed_classificacoes_recebimento', '2026-02-12 16:37:10.628837+00');
INSERT INTO public.schema_migrations VALUES ('050_recebimento_avulsos_e_batch', '2026-02-12 19:10:27.059289+00');


--
-- PostgreSQL database dump complete
--

\unrestrict YcgNkOYSlt3NckR8DPSQaGMK841pazG7K1AsIqc8kqo6K0fwcOB4Ng1efHKUx7f
