-- ==========================================================================
-- Baseline Schema — auto-generated by db/scripts/consolidate.mjs
-- Generated: 2026-02-13T14:56:53.957Z
-- Source: container recorda-postgres / recorda
-- ==========================================================================
--
-- PostgreSQL database dump
--

\restrict tZvBcePdEsgj9BjUozxsOhSBKLAqS7UovDYQmoViuw0ZXaWjObTTsTAR4TCoMdO

-- Dumped from database version 15.15
-- Dumped by pg_dump version 15.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- Name: etapa_fluxo; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.etapa_fluxo AS ENUM (
    'RECEBIMENTO',
    'PREPARACAO',
    'DIGITALIZACAO',
    'DIGITALIZACAO_COLORIDA',
    'CONFERENCIA',
    'MONTAGEM',
    'CONTROLE_QUALIDADE',
    'ENTREGA'
);


--
-- Name: kb_categoria; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.kb_categoria AS ENUM (
    'MANUAIS',
    'PROCEDIMENTOS_ETAPA',
    'CHECKLISTS_EXPLICADOS',
    'GLOSSARIO',
    'NORMAS_LEIS',
    'ATUALIZACOES_PROCESSO'
);


--
-- Name: kb_nivel_acesso; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.kb_nivel_acesso AS ENUM (
    'OPERADOR_ADMIN',
    'ADMIN'
);


--
-- Name: kb_status_documento; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.kb_status_documento AS ENUM (
    'ATIVO',
    'INATIVO'
);


--
-- Name: perfil_usuario; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.perfil_usuario AS ENUM (
    'operador',
    'supervisor',
    'administrador'
);


--
-- Name: resultado_cq_item; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.resultado_cq_item AS ENUM (
    'PENDENTE',
    'APROVADO',
    'REPROVADO'
);


--
-- Name: resultado_item_checklist; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.resultado_item_checklist AS ENUM (
    'CONFORME',
    'NAO_CONFORME_COM_TRATATIVA'
);


--
-- Name: status_artigo; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.status_artigo AS ENUM (
    'RASCUNHO',
    'PUBLICADO',
    'ARQUIVADO'
);


--
-- Name: status_checklist; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.status_checklist AS ENUM (
    'ABERTO',
    'CONCLUIDO'
);


--
-- Name: status_importacao; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.status_importacao AS ENUM (
    'PENDENTE',
    'PROCESSANDO',
    'CONCLUIDA',
    'ERRO',
    'CANCELADA'
);


--
-- Name: status_lote_cq; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.status_lote_cq AS ENUM (
    'ABERTO',
    'FECHADO'
);


--
-- Name: status_ocr; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.status_ocr AS ENUM (
    'PENDENTE',
    'PROCESSANDO',
    'CONCLUIDO',
    'ERRO'
);


--
-- Name: status_processo; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.status_processo AS ENUM (
    'ATIVO',
    'ARQUIVADO',
    'SUSPENSO',
    'CANCELADO'
);


--
-- Name: status_repositorio; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.status_repositorio AS ENUM (
    'RECEBIDO',
    'EM_PREPARACAO',
    'PREPARADO',
    'EM_DIGITALIZACAO',
    'DIGITALIZADO',
    'EM_CONFERENCIA',
    'CONFERIDO',
    'EM_MONTAGEM',
    'MONTADO',
    'AGUARDANDO_CQ_LOTE',
    'EM_CQ',
    'CQ_APROVADO',
    'CQ_REPROVADO',
    'EM_ENTREGA',
    'ENTREGUE'
);


--
-- Name: status_tratativa_excecao; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.status_tratativa_excecao AS ENUM (
    'ABERTA',
    'EM_TRATATIVA',
    'RESOLVIDA'
);


--
-- Name: tipo_apenso; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.tipo_apenso AS ENUM (
    'APENSO',
    'ANEXO',
    'APENSAMENTO'
);


--
-- Name: tipo_excecao_repositorio; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.tipo_excecao_repositorio AS ENUM (
    'MIDIA',
    'COLORIDO',
    'MAPA',
    'FRAGILIDADE'
);


--
-- Name: tipo_fonte; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.tipo_fonte AS ENUM (
    'SISTEMA',
    'PLANILHA',
    'MANUAL',
    'OCR',
    'API'
);


--
-- Name: tipo_importacao; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.tipo_importacao AS ENUM (
    'PLANILHA',
    'SISTEMA',
    'OCR',
    'MANUAL'
);


--
-- Name: tipo_movimentacao_armario; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.tipo_movimentacao_armario AS ENUM (
    'RETIRADA',
    'DEVOLUCAO'
);


--
-- Name: tipo_operacao; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.tipo_operacao AS ENUM (
    'INSERT',
    'UPDATE',
    'DELETE',
    'CANCEL'
);


--
-- Name: tipo_relatorio_operacional; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.tipo_relatorio_operacional AS ENUM (
    'RECEBIMENTO',
    'PRODUCAO',
    'ENTREGA'
);


--
-- Name: unidade_medida; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.unidade_medida AS ENUM (
    'PROCESSO',
    'VOLUME',
    'PAGINA',
    'DOCUMENTO'
);


--
-- Name: artigos_busca_trigger(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.artigos_busca_trigger() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.busca_vetor := 
        setweight(to_tsvector('portuguese', COALESCE(NEW.titulo, '')), 'A') ||
        setweight(to_tsvector('portuguese', COALESCE(NEW.resumo, '')), 'B') ||
        setweight(to_tsvector('portuguese', COALESCE(NEW.conteudo, '')), 'C');
    RETURN NEW;
END;
$$;


--
-- Name: audit_extract_registro_id(jsonb); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.audit_extract_registro_id(payload jsonb) RETURNS uuid
    LANGUAGE plpgsql
    AS $$
DECLARE
  raw_id TEXT;
BEGIN
  IF payload IS NULL THEN
    RETURN NULL;
  END IF;

  raw_id := COALESCE(
    payload->>'id',
    payload->>'id_repositorio_recorda'
  );

  IF raw_id IS NULL OR LENGTH(TRIM(raw_id)) = 0 THEN
    RETURN NULL;
  END IF;

  RETURN raw_id::UUID;
EXCEPTION
  WHEN invalid_text_representation THEN
    RETURN NULL;
END;
$$;


--
-- Name: audit_trigger_function(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.audit_trigger_function() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  old_data JSONB;
  new_data JSONB;
  op tipo_operacao;
  ref_id UUID;
BEGIN
  IF TG_OP = 'INSERT' THEN
    old_data := NULL;
    new_data := to_jsonb(NEW);
    op := 'INSERT';
    ref_id := audit_extract_registro_id(new_data);

    IF ref_id IS NULL THEN
      RAISE EXCEPTION 'Audit trigger: não foi possível extrair identificador do registro em % (INSERT)', TG_TABLE_NAME;
    END IF;

    INSERT INTO auditoria (tabela, registro_id, operacao, dados_anteriores, dados_novos)
    VALUES (TG_TABLE_NAME, ref_id, op, old_data, new_data);

    RETURN NEW;
  ELSIF TG_OP = 'UPDATE' THEN
    old_data := to_jsonb(OLD);
    new_data := to_jsonb(NEW);
    op := 'UPDATE';
    ref_id := COALESCE(audit_extract_registro_id(new_data), audit_extract_registro_id(old_data));

    IF ref_id IS NULL THEN
      RAISE EXCEPTION 'Audit trigger: não foi possível extrair identificador do registro em % (UPDATE)', TG_TABLE_NAME;
    END IF;

    INSERT INTO auditoria (tabela, registro_id, operacao, dados_anteriores, dados_novos)
    VALUES (TG_TABLE_NAME, ref_id, op, old_data, new_data);

    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    old_data := to_jsonb(OLD);
    new_data := NULL;
    op := 'DELETE';
    ref_id := audit_extract_registro_id(old_data);

    IF ref_id IS NULL THEN
      RAISE EXCEPTION 'Audit trigger: não foi possível extrair identificador do registro em % (DELETE)', TG_TABLE_NAME;
    END IF;

    INSERT INTO auditoria (tabela, registro_id, operacao, dados_anteriores, dados_novos)
    VALUES (TG_TABLE_NAME, ref_id, op, old_data, new_data);

    RETURN OLD;
  END IF;

  RETURN NULL;
END;
$$;


--
-- Name: check_delete_registros_producao(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.check_delete_registros_producao() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  IF OLD.importacao_id IS NULL THEN
    RAISE EXCEPTION 'Registro de produção é imutável; utilize cancelamento ao invés de excluir';
  END IF;
  RETURN OLD;
END;
$$;


--
-- Name: check_registros_producao_immutable(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.check_registros_producao_immutable() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF OLD.cancelado = FALSE AND NEW.cancelado = TRUE THEN
        -- Permitir apenas cancelamento
        IF NEW.processo_id != OLD.processo_id OR
           NEW.volume_id IS DISTINCT FROM OLD.volume_id OR
           NEW.etapa_id != OLD.etapa_id OR
           NEW.colaborador_id != OLD.colaborador_id OR
           NEW.fonte_dados_id != OLD.fonte_dados_id OR
           NEW.quantidade != OLD.quantidade OR
           NEW.data_registro != OLD.data_registro OR
           NEW.data_producao != OLD.data_producao OR
           NEW.observacao != OLD.observacao THEN
            RAISE EXCEPTION 'Campos imutáveis não podem ser alterados';
        END IF;
        RETURN NEW;
    ELSIF OLD.cancelado = TRUE THEN
        RAISE EXCEPTION 'Registro cancelado não pode ser alterado';
    ELSE
        RAISE EXCEPTION 'Registro de produção é imutável, apenas cancelamento é permitido';
    END IF;
END;
$$;


--
-- Name: fn_aplicar_resultado_cq_em_repositorios(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.fn_aplicar_resultado_cq_em_repositorios() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  item RECORD;
BEGIN
  IF NEW.status = 'FECHADO' AND OLD.status <> NEW.status THEN
    FOR item IN
      SELECT repositorio_id, resultado
      FROM lotes_controle_qualidade_itens
      WHERE lote_id = NEW.id
    LOOP
      IF item.resultado = 'APROVADO' THEN
        UPDATE repositorios
        SET status_atual = 'ENTREGUE',
            etapa_atual = 'ENTREGA'
        WHERE id_repositorio_recorda = item.repositorio_id;

        INSERT INTO historico_etapas (
          repositorio_id,
          etapa_origem,
          etapa_destino,
          status_origem,
          status_destino,
          usuario_id,
          detalhes
        )
        VALUES (
          item.repositorio_id,
          'CONTROLE_QUALIDADE',
          'ENTREGA',
          'EM_CQ',
          'ENTREGUE',
          NEW.auditor_id,
          jsonb_build_object('origem', 'lote_cq', 'lote_id', NEW.id)
        );
      ELSIF item.resultado = 'REPROVADO' THEN
        UPDATE repositorios
        SET status_atual = 'CQ_REPROVADO',
            etapa_atual = 'CONFERENCIA'
        WHERE id_repositorio_recorda = item.repositorio_id;

        INSERT INTO historico_etapas (
          repositorio_id,
          etapa_origem,
          etapa_destino,
          status_origem,
          status_destino,
          usuario_id,
          detalhes
        )
        VALUES (
          item.repositorio_id,
          'CONTROLE_QUALIDADE',
          'CONFERENCIA',
          'EM_CQ',
          'CQ_REPROVADO',
          NEW.auditor_id,
          jsonb_build_object('origem', 'lote_cq', 'lote_id', NEW.id)
        );
      END IF;
    END LOOP;
  END IF;

  RETURN NEW;
END;
$$;


--
-- Name: fn_validar_avanco_etapa_repositorio(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.fn_validar_avanco_etapa_repositorio() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  checklist_concluido BOOLEAN;
  ultima_movimentacao tipo_movimentacao_armario;
BEGIN
  IF NEW.etapa_atual <> OLD.etapa_atual THEN
    SELECT EXISTS (
      SELECT 1
      FROM checklists
      WHERE repositorio_id = OLD.id_repositorio_recorda
        AND etapa = OLD.etapa_atual
        AND status = 'CONCLUIDO'
    ) INTO checklist_concluido;

    IF NOT checklist_concluido THEN
      RAISE EXCEPTION 'Não é permitido avançar etapa sem checklist concluído da etapa %', OLD.etapa_atual;
    END IF;

    SELECT m.tipo_movimentacao
    INTO ultima_movimentacao
    FROM movimentacoes_armario m
    WHERE m.repositorio_id = OLD.id_repositorio_recorda
      AND m.etapa = OLD.etapa_atual
    ORDER BY m.data_movimentacao DESC
    LIMIT 1;

    IF ultima_movimentacao IS DISTINCT FROM 'DEVOLUCAO' THEN
      RAISE EXCEPTION 'Não é permitido avançar etapa sem devolução do repositório ao armário';
    END IF;

    NEW.historico_de_etapas :=
      COALESCE(OLD.historico_de_etapas, '[]'::jsonb) ||
      jsonb_build_array(
        jsonb_build_object(
          'etapa_origem', OLD.etapa_atual,
          'etapa_destino', NEW.etapa_atual,
          'status_origem', OLD.status_atual,
          'status_destino', NEW.status_atual,
          'data_evento', CURRENT_TIMESTAMP
        )
      );
  END IF;

  RETURN NEW;
END;
$$;


--
-- Name: fn_validar_conclusao_checklist(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.fn_validar_conclusao_checklist() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  total_obrigatorios INTEGER;
  total_preenchidos INTEGER;
BEGIN
  IF OLD.status = 'CONCLUIDO' AND NEW.status = 'ABERTO' THEN
    RAISE EXCEPTION 'Checklist concluído não pode ser reaberto';
  END IF;

  IF NEW.status = 'CONCLUIDO' AND OLD.status <> NEW.status THEN
    SELECT COUNT(*) INTO total_obrigatorios
    FROM checklist_modelos
    WHERE etapa = NEW.etapa
      AND obrigatorio = TRUE
      AND ativo = TRUE;

    -- Se não há modelos obrigatórios para a etapa, permitir conclusão
    IF total_obrigatorios > 0 THEN
      SELECT COUNT(*) INTO total_preenchidos
      FROM checklist_itens i
      JOIN checklist_modelos m ON m.id = i.modelo_id
      WHERE i.checklist_id = NEW.id
        AND m.etapa = NEW.etapa
        AND m.obrigatorio = TRUE
        AND m.ativo = TRUE;

      IF total_preenchidos < total_obrigatorios THEN
        RAISE EXCEPTION 'Checklist incompleto: % de % itens obrigatórios preenchidos', total_preenchidos, total_obrigatorios;
      END IF;
    END IF;

    NEW.data_conclusao := COALESCE(NEW.data_conclusao, CURRENT_TIMESTAMP);
    NEW.ativo := FALSE;
  END IF;

  RETURN NEW;
END;
$$;


--
-- Name: fn_validar_fechamento_lote_cq(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.fn_validar_fechamento_lote_cq() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  total_itens INTEGER;
  total_pendentes INTEGER;
BEGIN
  IF NEW.status = 'FECHADO' AND OLD.status <> NEW.status THEN
    SELECT COUNT(*) INTO total_itens
    FROM lotes_controle_qualidade_itens
    WHERE lote_id = NEW.id;

    IF total_itens <> 10 THEN
      RAISE EXCEPTION 'Lote de CQ deve conter exatamente 10 repositórios. Total atual: %', total_itens;
    END IF;

    SELECT COUNT(*) INTO total_pendentes
    FROM lotes_controle_qualidade_itens
    WHERE lote_id = NEW.id
      AND resultado = 'PENDENTE';

    IF total_pendentes > 0 THEN
      RAISE EXCEPTION 'Não é possível fechar lote de CQ com itens pendentes';
    END IF;

    NEW.data_fechamento := COALESCE(NEW.data_fechamento, CURRENT_TIMESTAMP);
  END IF;

  RETURN NEW;
END;
$$;


--
-- Name: fn_validar_producao_com_checklist_ativo(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.fn_validar_producao_com_checklist_ativo() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  checklist_valido INTEGER;
BEGIN
  SELECT COUNT(*) INTO checklist_valido
  FROM checklists
  WHERE id = NEW.checklist_id
    AND repositorio_id = NEW.repositorio_id
    AND etapa = NEW.etapa
    AND status = 'ABERTO'
    AND ativo = TRUE;

  IF checklist_valido = 0 THEN
    RAISE EXCEPTION 'Produção exige checklist ativo da mesma etapa e repositório';
  END IF;

  RETURN NEW;
END;
$$;


--
-- Name: update_timestamp(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.update_timestamp() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.atualizado_em = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;


--
-- Name: update_updated_at_column(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.update_updated_at_column() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
      NEW.atualizado_em = CURRENT_TIMESTAMP;
      RETURN NEW;
    END;
    $$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: armarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.armarios (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    codigo character varying(50) NOT NULL,
    descricao character varying(255) DEFAULT ''::character varying NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    criado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    atualizado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT armarios_codigo_not_empty CHECK ((length(TRIM(BOTH FROM codigo)) > 0))
);


--
-- Name: auditoria; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auditoria (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    tabela character varying(100) NOT NULL,
    registro_id uuid NOT NULL,
    operacao public.tipo_operacao NOT NULL,
    dados_anteriores jsonb,
    dados_novos jsonb,
    colaborador_id uuid,
    ip_origem character varying(45),
    user_agent text,
    data_operacao timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT auditoria_data_not_future CHECK ((data_operacao <= CURRENT_TIMESTAMP)),
    CONSTRAINT auditoria_tabela_not_empty CHECK ((length(TRIM(BOTH FROM tabela)) > 0))
);


--
-- Name: checklist_itens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.checklist_itens (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    checklist_id uuid NOT NULL,
    modelo_id uuid NOT NULL,
    resultado public.resultado_item_checklist NOT NULL,
    observacao character varying(1000) DEFAULT ''::character varying NOT NULL,
    responsavel_id uuid NOT NULL,
    data_hora timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT checklist_item_observacao_nonconforme CHECK (((resultado = 'CONFORME'::public.resultado_item_checklist) OR (length(TRIM(BOTH FROM observacao)) > 0)))
);


--
-- Name: checklist_modelos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.checklist_modelos (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    etapa public.etapa_fluxo NOT NULL,
    codigo character varying(100) NOT NULL,
    descricao character varying(400) NOT NULL,
    obrigatorio boolean DEFAULT true NOT NULL,
    ordem integer NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    criado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    atualizado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT checklist_modelo_codigo_not_empty CHECK ((length(TRIM(BOTH FROM codigo)) > 0)),
    CONSTRAINT checklist_modelo_descricao_not_empty CHECK ((length(TRIM(BOTH FROM descricao)) > 0)),
    CONSTRAINT checklist_modelo_ordem_non_negative CHECK ((ordem >= 0))
);


--
-- Name: checklists; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.checklists (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    repositorio_id uuid NOT NULL,
    etapa public.etapa_fluxo NOT NULL,
    status public.status_checklist DEFAULT 'ABERTO'::public.status_checklist NOT NULL,
    observacao character varying(1000) DEFAULT ''::character varying NOT NULL,
    responsavel_id uuid NOT NULL,
    data_abertura timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    data_conclusao timestamp with time zone,
    ativo boolean DEFAULT true NOT NULL,
    criado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    atualizado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT checklists_status_consistencia CHECK ((((status = 'ABERTO'::public.status_checklist) AND (data_conclusao IS NULL) AND (ativo = true)) OR ((status = 'CONCLUIDO'::public.status_checklist) AND (data_conclusao IS NOT NULL) AND (ativo = false))))
);


--
-- Name: classificacoes_recebimento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.classificacoes_recebimento (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    nome character varying(500) NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    criado_por uuid NOT NULL,
    criado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT classif_receb_nome_not_empty CHECK ((length(TRIM(BOTH FROM nome)) > 0))
);


--
-- Name: colaboradores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.colaboradores (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    nome character varying(255) NOT NULL,
    matricula character varying(20) NOT NULL,
    coordenadoria_id uuid NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    criado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    atualizado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    email character varying(255),
    CONSTRAINT colaboradores_matricula_not_empty CHECK ((length(TRIM(BOTH FROM matricula)) > 0)),
    CONSTRAINT colaboradores_nome_min_length CHECK ((length(TRIM(BOTH FROM nome)) >= 2))
);


--
-- Name: configuracao_empresa; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.configuracao_empresa (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    nome character varying(200) DEFAULT ''::character varying NOT NULL,
    cnpj character varying(20) DEFAULT ''::character varying,
    endereco text DEFAULT ''::text,
    telefone character varying(30) DEFAULT ''::character varying,
    email character varying(100) DEFAULT ''::character varying,
    logo_url text DEFAULT ''::text,
    exibir_logo_relatorio boolean DEFAULT true,
    exibir_endereco_relatorio boolean DEFAULT true,
    exibir_contato_relatorio boolean DEFAULT true,
    data_criacao timestamp with time zone DEFAULT now(),
    data_atualizacao timestamp with time zone DEFAULT now()
);


--
-- Name: configuracao_projetos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.configuracao_projetos (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    nome character varying(200) NOT NULL,
    descricao text DEFAULT ''::text,
    ativo boolean DEFAULT true NOT NULL,
    criado_em timestamp with time zone DEFAULT now() NOT NULL,
    atualizado_em timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: coordenadorias; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.coordenadorias (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    nome character varying(255) NOT NULL,
    sigla character varying(20) NOT NULL,
    ativa boolean DEFAULT true NOT NULL,
    criado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    atualizado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT coordenadorias_nome_min_length CHECK ((length(TRIM(BOTH FROM nome)) >= 2)),
    CONSTRAINT coordenadorias_sigla_not_empty CHECK ((length(TRIM(BOTH FROM sigla)) > 0))
);


--
-- Name: etapas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.etapas (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    nome character varying(255) NOT NULL,
    descricao text DEFAULT ''::text NOT NULL,
    unidade public.unidade_medida NOT NULL,
    ordem integer NOT NULL,
    ativa boolean DEFAULT true NOT NULL,
    criado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    atualizado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT etapas_nome_min_length CHECK ((length(TRIM(BOTH FROM nome)) >= 2)),
    CONSTRAINT etapas_ordem_non_negative CHECK ((ordem >= 0))
);


--
-- Name: excecoes_repositorio; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.excecoes_repositorio (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    repositorio_id uuid NOT NULL,
    etapa public.etapa_fluxo NOT NULL,
    tipo_excecao public.tipo_excecao_repositorio NOT NULL,
    status_tratativa public.status_tratativa_excecao DEFAULT 'ABERTA'::public.status_tratativa_excecao NOT NULL,
    detalhes jsonb DEFAULT '{}'::jsonb NOT NULL,
    responsavel_id uuid NOT NULL,
    data_registro timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    data_resolucao timestamp with time zone,
    CONSTRAINT excecao_resolucao_consistencia CHECK ((((status_tratativa = 'RESOLVIDA'::public.status_tratativa_excecao) AND (data_resolucao IS NOT NULL)) OR ((status_tratativa = ANY (ARRAY['ABERTA'::public.status_tratativa_excecao, 'EM_TRATATIVA'::public.status_tratativa_excecao])) AND (data_resolucao IS NULL))))
);


--
-- Name: historico_etapas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.historico_etapas (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    repositorio_id uuid NOT NULL,
    etapa_origem public.etapa_fluxo,
    etapa_destino public.etapa_fluxo NOT NULL,
    status_origem public.status_repositorio,
    status_destino public.status_repositorio NOT NULL,
    usuario_id uuid,
    data_evento timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    detalhes jsonb DEFAULT '{}'::jsonb NOT NULL
);


--
-- Name: importacoes_legado_operacional; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.importacoes_legado_operacional (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    tipo character varying(40) DEFAULT 'RECEBIMENTO'::character varying NOT NULL,
    total_registros integer DEFAULT 0 NOT NULL,
    registros_sucesso integer DEFAULT 0 NOT NULL,
    registros_erro integer DEFAULT 0 NOT NULL,
    detalhes_erros jsonb DEFAULT '[]'::jsonb NOT NULL,
    usuario_destino_id uuid NOT NULL,
    executado_por uuid NOT NULL,
    criado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT import_legado_consistencia CHECK (((registros_sucesso + registros_erro) <= total_registros)),
    CONSTRAINT import_legado_erro_non_negative CHECK ((registros_erro >= 0)),
    CONSTRAINT import_legado_sucesso_non_negative CHECK ((registros_sucesso >= 0)),
    CONSTRAINT import_legado_total_non_negative CHECK ((total_registros >= 0))
);


--
-- Name: kb_documento_etapas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.kb_documento_etapas (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    documento_id uuid NOT NULL,
    etapa public.etapa_fluxo NOT NULL,
    criado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: kb_documento_versoes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.kb_documento_versoes (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    documento_id uuid NOT NULL,
    versao integer NOT NULL,
    conteudo text NOT NULL,
    resumo_alteracao character varying(500) DEFAULT ''::character varying NOT NULL,
    publicado_por uuid NOT NULL,
    publicado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT kb_conteudo_not_empty CHECK ((length(TRIM(BOTH FROM conteudo)) > 0)),
    CONSTRAINT kb_versao_positive CHECK ((versao > 0))
);


--
-- Name: kb_documentos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.kb_documentos (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    codigo character varying(100) NOT NULL,
    titulo character varying(255) NOT NULL,
    categoria public.kb_categoria NOT NULL,
    descricao character varying(1000) DEFAULT ''::character varying NOT NULL,
    status public.kb_status_documento DEFAULT 'ATIVO'::public.kb_status_documento NOT NULL,
    nivel_acesso public.kb_nivel_acesso DEFAULT 'OPERADOR_ADMIN'::public.kb_nivel_acesso NOT NULL,
    versao_atual_id uuid,
    criado_por uuid NOT NULL,
    criado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    atualizado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT kb_documentos_codigo_not_empty CHECK ((length(TRIM(BOTH FROM codigo)) > 0)),
    CONSTRAINT kb_documentos_titulo_not_empty CHECK ((length(TRIM(BOTH FROM titulo)) > 0))
);


--
-- Name: lotes_controle_qualidade; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lotes_controle_qualidade (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    codigo character varying(80) NOT NULL,
    status public.status_lote_cq DEFAULT 'ABERTO'::public.status_lote_cq NOT NULL,
    auditor_id uuid NOT NULL,
    data_criacao timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    data_fechamento timestamp with time zone,
    CONSTRAINT lote_cq_fechamento_consistencia CHECK ((((status = 'ABERTO'::public.status_lote_cq) AND (data_fechamento IS NULL)) OR ((status = 'FECHADO'::public.status_lote_cq) AND (data_fechamento IS NOT NULL))))
);


--
-- Name: lotes_controle_qualidade_itens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lotes_controle_qualidade_itens (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    lote_id uuid NOT NULL,
    repositorio_id uuid NOT NULL,
    ordem smallint NOT NULL,
    resultado public.resultado_cq_item DEFAULT 'PENDENTE'::public.resultado_cq_item NOT NULL,
    motivo_codigo character varying(100),
    auditor_id uuid,
    data_auditoria timestamp with time zone,
    CONSTRAINT lote_item_motivo_consistencia CHECK ((((resultado = 'REPROVADO'::public.resultado_cq_item) AND (motivo_codigo IS NOT NULL)) OR ((resultado = ANY (ARRAY['PENDENTE'::public.resultado_cq_item, 'APROVADO'::public.resultado_cq_item])) AND (motivo_codigo IS NULL)))),
    CONSTRAINT lote_item_ordem_range CHECK (((ordem >= 1) AND (ordem <= 10)))
);


--
-- Name: mapeamentos_importacao; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mapeamentos_importacao (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    nome character varying(255) NOT NULL,
    mapeamento jsonb NOT NULL,
    criado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    atualizado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT mapeamentos_importacao_nome_not_empty CHECK ((length(TRIM(BOTH FROM nome)) > 0))
);


--
-- Name: metas_producao; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.metas_producao (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    etapa_id uuid NOT NULL,
    meta_diaria integer DEFAULT 0 NOT NULL,
    meta_mensal integer DEFAULT 0 NOT NULL,
    ativa boolean DEFAULT true NOT NULL,
    criado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    atualizado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT metas_diaria_non_negative CHECK ((meta_diaria >= 0)),
    CONSTRAINT metas_mensal_non_negative CHECK ((meta_mensal >= 0))
);


--
-- Name: movimentacoes_armario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.movimentacoes_armario (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    repositorio_id uuid NOT NULL,
    armario_id uuid NOT NULL,
    etapa public.etapa_fluxo NOT NULL,
    tipo_movimentacao public.tipo_movimentacao_armario NOT NULL,
    usuario_id uuid NOT NULL,
    data_movimentacao timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    observacao character varying(500) DEFAULT ''::character varying NOT NULL
);


--
-- Name: producao_repositorio; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.producao_repositorio (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    repositorio_id uuid NOT NULL,
    etapa public.etapa_fluxo NOT NULL,
    checklist_id uuid NOT NULL,
    usuario_id uuid NOT NULL,
    quantidade integer DEFAULT 1 NOT NULL,
    marcadores jsonb DEFAULT '{}'::jsonb NOT NULL,
    data_producao timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT producao_quantidade_positive CHECK ((quantidade > 0))
);


--
-- Name: recebimento_apenso_volumes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recebimento_apenso_volumes (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    apenso_id uuid NOT NULL,
    numero_volume integer NOT NULL,
    volume_total integer DEFAULT 0 NOT NULL,
    ocr_confianca numeric(5,4),
    texto_extraido text DEFAULT ''::text NOT NULL,
    imagem_path character varying(500),
    origem character varying(20) DEFAULT 'MANUAL'::character varying NOT NULL,
    observacao text DEFAULT ''::text NOT NULL,
    criado_por uuid NOT NULL,
    criado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT receb_apvol_numero_positive CHECK ((numero_volume > 0)),
    CONSTRAINT receb_apvol_origem_valid CHECK (((origem)::text = ANY ((ARRAY['MANUAL'::character varying, 'OCR'::character varying, 'LEGADO'::character varying])::text[])))
);


--
-- Name: recebimento_apensos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recebimento_apensos (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    processo_principal_id uuid NOT NULL,
    protocolo character varying(60) NOT NULL,
    data_protocolo timestamp with time zone,
    interessado character varying(500),
    assunto character varying(1000),
    resumo text,
    setor_origem character varying(500),
    setor_destino character varying(500),
    codigo_barras character varying(100),
    volume_atual integer DEFAULT 1 NOT NULL,
    volume_total integer DEFAULT 0 NOT NULL,
    origem character varying(20) DEFAULT 'MANUAL'::character varying NOT NULL,
    ocr_confianca numeric(5,4),
    texto_extraido text DEFAULT ''::text NOT NULL,
    imagem_path character varying(500),
    observacao text DEFAULT ''::text NOT NULL,
    criado_por uuid NOT NULL,
    criado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT receb_apenso_origem_valid CHECK (((origem)::text = ANY ((ARRAY['MANUAL'::character varying, 'OCR'::character varying, 'LEGADO'::character varying])::text[]))),
    CONSTRAINT receb_apenso_protocolo_not_empty CHECK ((length(TRIM(BOTH FROM protocolo)) > 0)),
    CONSTRAINT receb_apenso_volume_atual_positive CHECK ((volume_atual > 0)),
    CONSTRAINT receb_apenso_volume_total_non_negative CHECK ((volume_total >= 0))
);


--
-- Name: recebimento_documentos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recebimento_documentos (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    repositorio_id uuid NOT NULL,
    processo character varying(120) NOT NULL,
    interessado character varying(255) NOT NULL,
    numero_caixas integer DEFAULT 1 NOT NULL,
    volume character varying(50) DEFAULT '1'::character varying NOT NULL,
    caixa_nova boolean DEFAULT false NOT NULL,
    origem character varying(20) DEFAULT 'MANUAL'::character varying NOT NULL,
    ocr_confianca numeric(5,4),
    texto_extraido text DEFAULT ''::text NOT NULL,
    imagem_path character varying(500),
    criado_por uuid NOT NULL,
    criado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT receb_doc_interessado_not_empty CHECK ((length(TRIM(BOTH FROM interessado)) > 0)),
    CONSTRAINT receb_doc_numero_caixas_positive CHECK ((numero_caixas > 0)),
    CONSTRAINT receb_doc_ocr_range CHECK (((ocr_confianca IS NULL) OR ((ocr_confianca >= (0)::numeric) AND (ocr_confianca <= (1)::numeric)))),
    CONSTRAINT receb_doc_origem_valid CHECK (((origem)::text = ANY ((ARRAY['MANUAL'::character varying, 'OCR'::character varying, 'LEGADO'::character varying])::text[]))),
    CONSTRAINT receb_doc_processo_not_empty CHECK ((length(TRIM(BOTH FROM processo)) > 0))
);


--
-- Name: recebimento_processos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recebimento_processos (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    repositorio_id uuid,
    protocolo character varying(60) NOT NULL,
    data_protocolo timestamp with time zone,
    orgao character varying(500),
    interessado character varying(500) NOT NULL,
    assunto character varying(1000),
    resumo text,
    setor_origem character varying(500),
    setor_destino character varying(500),
    codigo_barras character varying(100),
    volume_atual integer DEFAULT 1 NOT NULL,
    volume_total integer DEFAULT 0 NOT NULL,
    numero_caixas integer DEFAULT 1 NOT NULL,
    caixa_nova boolean DEFAULT false NOT NULL,
    origem character varying(20) DEFAULT 'MANUAL'::character varying NOT NULL,
    ocr_confianca numeric(5,4),
    texto_extraido text DEFAULT ''::text NOT NULL,
    imagem_path character varying(500),
    criado_por uuid NOT NULL,
    criado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    atualizado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    setor_id uuid,
    classificacao_id uuid,
    observacao text DEFAULT ''::text NOT NULL,
    CONSTRAINT receb_proc_interessado_not_empty CHECK ((length(TRIM(BOTH FROM interessado)) > 0)),
    CONSTRAINT receb_proc_numero_caixas_positive CHECK ((numero_caixas > 0)),
    CONSTRAINT receb_proc_origem_valid CHECK (((origem)::text = ANY ((ARRAY['MANUAL'::character varying, 'OCR'::character varying, 'LEGADO'::character varying])::text[]))),
    CONSTRAINT receb_proc_protocolo_not_empty CHECK ((length(TRIM(BOTH FROM protocolo)) > 0)),
    CONSTRAINT receb_proc_volume_atual_positive CHECK ((volume_atual > 0)),
    CONSTRAINT receb_proc_volume_total_non_negative CHECK ((volume_total >= 0))
);


--
-- Name: recebimento_volumes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recebimento_volumes (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    processo_id uuid NOT NULL,
    numero_volume integer NOT NULL,
    volume_total integer DEFAULT 0 NOT NULL,
    ocr_confianca numeric(5,4),
    texto_extraido text DEFAULT ''::text NOT NULL,
    imagem_path character varying(500),
    origem character varying(20) DEFAULT 'MANUAL'::character varying NOT NULL,
    observacao text DEFAULT ''::text NOT NULL,
    criado_por uuid NOT NULL,
    criado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT receb_vol_numero_positive CHECK ((numero_volume > 0)),
    CONSTRAINT receb_vol_origem_valid CHECK (((origem)::text = ANY ((ARRAY['MANUAL'::character varying, 'OCR'::character varying, 'LEGADO'::character varying])::text[])))
);


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_tokens (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    usuario_id uuid NOT NULL,
    token_hash character varying(255) NOT NULL,
    expira_em timestamp with time zone NOT NULL,
    revogado boolean DEFAULT false NOT NULL,
    criado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT refresh_tokens_expira_futuro CHECK ((expira_em > criado_em))
);


--
-- Name: registros_producao; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.registros_producao (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    processo_id uuid NOT NULL,
    volume_id uuid,
    etapa_id uuid NOT NULL,
    colaborador_id uuid NOT NULL,
    fonte_dados_id uuid NOT NULL,
    quantidade integer NOT NULL,
    data_registro timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    data_producao timestamp with time zone NOT NULL,
    observacao text DEFAULT ''::text NOT NULL,
    cancelado boolean DEFAULT false NOT NULL,
    motivo_cancelamento text,
    data_cancelamento timestamp with time zone,
    cancelado_por uuid,
    criado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    data_criacao timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    importacao_id uuid,
    CONSTRAINT registros_cancelamento_consistency CHECK ((((cancelado = false) AND (motivo_cancelamento IS NULL) AND (data_cancelamento IS NULL) AND (cancelado_por IS NULL)) OR ((cancelado = true) AND (motivo_cancelamento IS NOT NULL) AND (data_cancelamento IS NOT NULL)))),
    CONSTRAINT registros_data_producao_not_future CHECK ((data_producao <= CURRENT_TIMESTAMP)),
    CONSTRAINT registros_data_registro_not_future CHECK ((data_registro <= CURRENT_TIMESTAMP)),
    CONSTRAINT registros_quantidade_positive CHECK ((quantidade > 0))
);


--
-- Name: relatorios_operacionais; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.relatorios_operacionais (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    tipo public.tipo_relatorio_operacional NOT NULL,
    repositorio_id uuid,
    lote_id uuid,
    arquivo_path character varying(500) NOT NULL,
    hash_arquivo character varying(128) NOT NULL,
    dados_snapshot jsonb DEFAULT '{}'::jsonb NOT NULL,
    gerado_por uuid NOT NULL,
    gerado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT relatorio_alvo_consistencia CHECK ((((tipo = 'ENTREGA'::public.tipo_relatorio_operacional) AND (lote_id IS NOT NULL) AND (repositorio_id IS NULL)) OR ((tipo = ANY (ARRAY['RECEBIMENTO'::public.tipo_relatorio_operacional, 'PRODUCAO'::public.tipo_relatorio_operacional])) AND (repositorio_id IS NOT NULL))))
);


--
-- Name: repositorios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.repositorios (
    id_repositorio_recorda uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    id_repositorio_ged character varying(100) NOT NULL,
    orgao character varying(255) NOT NULL,
    projeto character varying(255) NOT NULL,
    status_atual public.status_repositorio DEFAULT 'RECEBIDO'::public.status_repositorio NOT NULL,
    etapa_atual public.etapa_fluxo DEFAULT 'RECEBIMENTO'::public.etapa_fluxo NOT NULL,
    localizacao_fisica_armario_id uuid,
    data_criacao timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    historico_de_etapas jsonb DEFAULT '[]'::jsonb NOT NULL,
    criado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    atualizado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    data_entrega timestamp with time zone,
    seadesk_confirmado_em timestamp with time zone,
    seadesk_confirmado_por uuid,
    CONSTRAINT repositorio_ged_not_empty CHECK ((length(TRIM(BOTH FROM id_repositorio_ged)) > 0)),
    CONSTRAINT repositorio_orgao_not_empty CHECK ((length(TRIM(BOTH FROM orgao)) > 0)),
    CONSTRAINT repositorio_projeto_not_empty CHECK ((length(TRIM(BOTH FROM projeto)) > 0))
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version character varying(255) NOT NULL,
    applied_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: setores_recebimento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.setores_recebimento (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    nome character varying(300) NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    criado_por uuid NOT NULL,
    criado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT setor_receb_nome_not_empty CHECK ((length(TRIM(BOTH FROM nome)) > 0))
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    nome character varying(200) NOT NULL,
    email character varying(255) NOT NULL,
    senha_hash character varying(255) NOT NULL,
    perfil public.perfil_usuario DEFAULT 'operador'::public.perfil_usuario NOT NULL,
    coordenadoria_id uuid,
    ativo boolean DEFAULT true NOT NULL,
    ultimo_acesso timestamp with time zone,
    criado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    atualizado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT usuarios_email_valid CHECK (((email)::text ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text)),
    CONSTRAINT usuarios_nome_not_empty CHECK ((length(TRIM(BOTH FROM nome)) >= 2))
);


--
-- Name: armarios armarios_codigo_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.armarios
    ADD CONSTRAINT armarios_codigo_key UNIQUE (codigo);


--
-- Name: armarios armarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.armarios
    ADD CONSTRAINT armarios_pkey PRIMARY KEY (id);


--
-- Name: auditoria auditoria_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auditoria
    ADD CONSTRAINT auditoria_pkey PRIMARY KEY (id);


--
-- Name: checklist_itens checklist_itens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checklist_itens
    ADD CONSTRAINT checklist_itens_pkey PRIMARY KEY (id);


--
-- Name: checklist_modelos checklist_modelos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checklist_modelos
    ADD CONSTRAINT checklist_modelos_pkey PRIMARY KEY (id);


--
-- Name: checklists checklists_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checklists
    ADD CONSTRAINT checklists_pkey PRIMARY KEY (id);


--
-- Name: classificacoes_recebimento classificacoes_recebimento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classificacoes_recebimento
    ADD CONSTRAINT classificacoes_recebimento_pkey PRIMARY KEY (id);


--
-- Name: colaboradores colaboradores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.colaboradores
    ADD CONSTRAINT colaboradores_pkey PRIMARY KEY (id);


--
-- Name: configuracao_empresa configuracao_empresa_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.configuracao_empresa
    ADD CONSTRAINT configuracao_empresa_pkey PRIMARY KEY (id);


--
-- Name: configuracao_projetos configuracao_projetos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.configuracao_projetos
    ADD CONSTRAINT configuracao_projetos_pkey PRIMARY KEY (id);


--
-- Name: coordenadorias coordenadorias_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coordenadorias
    ADD CONSTRAINT coordenadorias_pkey PRIMARY KEY (id);


--
-- Name: etapas etapas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.etapas
    ADD CONSTRAINT etapas_pkey PRIMARY KEY (id);


--
-- Name: excecoes_repositorio excecoes_repositorio_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.excecoes_repositorio
    ADD CONSTRAINT excecoes_repositorio_pkey PRIMARY KEY (id);


--
-- Name: historico_etapas historico_etapas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historico_etapas
    ADD CONSTRAINT historico_etapas_pkey PRIMARY KEY (id);


--
-- Name: importacoes_legado_operacional importacoes_legado_operacional_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.importacoes_legado_operacional
    ADD CONSTRAINT importacoes_legado_operacional_pkey PRIMARY KEY (id);


--
-- Name: kb_documento_etapas kb_documento_etapas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kb_documento_etapas
    ADD CONSTRAINT kb_documento_etapas_pkey PRIMARY KEY (id);


--
-- Name: kb_documento_versoes kb_documento_versoes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kb_documento_versoes
    ADD CONSTRAINT kb_documento_versoes_pkey PRIMARY KEY (id);


--
-- Name: kb_documentos kb_documentos_codigo_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kb_documentos
    ADD CONSTRAINT kb_documentos_codigo_key UNIQUE (codigo);


--
-- Name: kb_documentos kb_documentos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kb_documentos
    ADD CONSTRAINT kb_documentos_pkey PRIMARY KEY (id);


--
-- Name: lotes_controle_qualidade lotes_controle_qualidade_codigo_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lotes_controle_qualidade
    ADD CONSTRAINT lotes_controle_qualidade_codigo_key UNIQUE (codigo);


--
-- Name: lotes_controle_qualidade_itens lotes_controle_qualidade_itens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lotes_controle_qualidade_itens
    ADD CONSTRAINT lotes_controle_qualidade_itens_pkey PRIMARY KEY (id);


--
-- Name: lotes_controle_qualidade lotes_controle_qualidade_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lotes_controle_qualidade
    ADD CONSTRAINT lotes_controle_qualidade_pkey PRIMARY KEY (id);


--
-- Name: mapeamentos_importacao mapeamentos_importacao_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mapeamentos_importacao
    ADD CONSTRAINT mapeamentos_importacao_pkey PRIMARY KEY (id);


--
-- Name: metas_producao metas_producao_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.metas_producao
    ADD CONSTRAINT metas_producao_pkey PRIMARY KEY (id);


--
-- Name: movimentacoes_armario movimentacoes_armario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movimentacoes_armario
    ADD CONSTRAINT movimentacoes_armario_pkey PRIMARY KEY (id);


--
-- Name: producao_repositorio producao_repositorio_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.producao_repositorio
    ADD CONSTRAINT producao_repositorio_pkey PRIMARY KEY (id);


--
-- Name: recebimento_apenso_volumes recebimento_apenso_volumes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recebimento_apenso_volumes
    ADD CONSTRAINT recebimento_apenso_volumes_pkey PRIMARY KEY (id);


--
-- Name: recebimento_apensos recebimento_apensos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recebimento_apensos
    ADD CONSTRAINT recebimento_apensos_pkey PRIMARY KEY (id);


--
-- Name: recebimento_documentos recebimento_documentos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recebimento_documentos
    ADD CONSTRAINT recebimento_documentos_pkey PRIMARY KEY (id);


--
-- Name: recebimento_processos recebimento_processos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recebimento_processos
    ADD CONSTRAINT recebimento_processos_pkey PRIMARY KEY (id);


--
-- Name: recebimento_volumes recebimento_volumes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recebimento_volumes
    ADD CONSTRAINT recebimento_volumes_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: registros_producao registros_producao_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registros_producao
    ADD CONSTRAINT registros_producao_pkey PRIMARY KEY (id);


--
-- Name: relatorios_operacionais relatorios_operacionais_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.relatorios_operacionais
    ADD CONSTRAINT relatorios_operacionais_pkey PRIMARY KEY (id);


--
-- Name: repositorios repositorios_id_repositorio_ged_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.repositorios
    ADD CONSTRAINT repositorios_id_repositorio_ged_key UNIQUE (id_repositorio_ged);


--
-- Name: repositorios repositorios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.repositorios
    ADD CONSTRAINT repositorios_pkey PRIMARY KEY (id_repositorio_recorda);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: setores_recebimento setores_recebimento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.setores_recebimento
    ADD CONSTRAINT setores_recebimento_pkey PRIMARY KEY (id);


--
-- Name: checklist_itens uk_checklist_item_modelo; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checklist_itens
    ADD CONSTRAINT uk_checklist_item_modelo UNIQUE (checklist_id, modelo_id);


--
-- Name: checklist_modelos uk_checklist_modelo_etapa_codigo; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checklist_modelos
    ADD CONSTRAINT uk_checklist_modelo_etapa_codigo UNIQUE (etapa, codigo);


--
-- Name: kb_documento_etapas uk_kb_documento_etapa; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kb_documento_etapas
    ADD CONSTRAINT uk_kb_documento_etapa UNIQUE (documento_id, etapa);


--
-- Name: kb_documento_versoes uk_kb_documento_versao; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kb_documento_versoes
    ADD CONSTRAINT uk_kb_documento_versao UNIQUE (documento_id, versao);


--
-- Name: lotes_controle_qualidade_itens uk_lote_item_ordem; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lotes_controle_qualidade_itens
    ADD CONSTRAINT uk_lote_item_ordem UNIQUE (lote_id, ordem);


--
-- Name: lotes_controle_qualidade_itens uk_lote_item_repositorio; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lotes_controle_qualidade_itens
    ADD CONSTRAINT uk_lote_item_repositorio UNIQUE (lote_id, repositorio_id);


--
-- Name: usuarios usuarios_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_email_key UNIQUE (email);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- Name: idx_armarios_ativo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_armarios_ativo ON public.armarios USING btree (ativo) WHERE (ativo = true);


--
-- Name: idx_auditoria_colaborador; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auditoria_colaborador ON public.auditoria USING btree (colaborador_id) WHERE (colaborador_id IS NOT NULL);


--
-- Name: idx_auditoria_data; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auditoria_data ON public.auditoria USING btree (data_operacao);


--
-- Name: idx_auditoria_operacao; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auditoria_operacao ON public.auditoria USING btree (operacao);


--
-- Name: idx_auditoria_registro; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auditoria_registro ON public.auditoria USING btree (registro_id);


--
-- Name: idx_auditoria_tabela; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auditoria_tabela ON public.auditoria USING btree (tabela);


--
-- Name: idx_auditoria_tabela_registro; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auditoria_tabela_registro ON public.auditoria USING btree (tabela, registro_id);


--
-- Name: idx_checklist_itens_checklist; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_checklist_itens_checklist ON public.checklist_itens USING btree (checklist_id);


--
-- Name: idx_checklist_modelos_etapa_ativo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_checklist_modelos_etapa_ativo ON public.checklist_modelos USING btree (etapa, ativo);


--
-- Name: idx_checklists_repositorio_etapa; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_checklists_repositorio_etapa ON public.checklists USING btree (repositorio_id, etapa);


--
-- Name: idx_checklists_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_checklists_status ON public.checklists USING btree (status);


--
-- Name: idx_classif_receb_nome_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_classif_receb_nome_unique ON public.classificacoes_recebimento USING btree (lower(TRIM(BOTH FROM nome))) WHERE (ativo = true);


--
-- Name: idx_colaboradores_ativo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_colaboradores_ativo ON public.colaboradores USING btree (ativo) WHERE (ativo = true);


--
-- Name: idx_colaboradores_coordenadoria; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_colaboradores_coordenadoria ON public.colaboradores USING btree (coordenadoria_id);


--
-- Name: idx_colaboradores_email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_colaboradores_email ON public.colaboradores USING btree (email);


--
-- Name: idx_colaboradores_matricula; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_colaboradores_matricula ON public.colaboradores USING btree (matricula);


--
-- Name: idx_configuracao_empresa_singleton; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_configuracao_empresa_singleton ON public.configuracao_empresa USING btree ((true));


--
-- Name: idx_configuracao_projetos_ativo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_configuracao_projetos_ativo ON public.configuracao_projetos USING btree (ativo);


--
-- Name: idx_coordenadorias_ativa; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_coordenadorias_ativa ON public.coordenadorias USING btree (ativa) WHERE (ativa = true);


--
-- Name: idx_coordenadorias_sigla; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_coordenadorias_sigla ON public.coordenadorias USING btree (upper((sigla)::text));


--
-- Name: idx_etapas_ativa; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_etapas_ativa ON public.etapas USING btree (ativa) WHERE (ativa = true);


--
-- Name: idx_etapas_ordem; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_etapas_ordem ON public.etapas USING btree (ordem) WHERE (ativa = true);


--
-- Name: idx_excecoes_repositorio; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_excecoes_repositorio ON public.excecoes_repositorio USING btree (repositorio_id, etapa);


--
-- Name: idx_excecoes_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_excecoes_status ON public.excecoes_repositorio USING btree (status_tratativa);


--
-- Name: idx_historico_repositorio_data; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_historico_repositorio_data ON public.historico_etapas USING btree (repositorio_id, data_evento DESC);


--
-- Name: idx_import_legado_criado_em; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_import_legado_criado_em ON public.importacoes_legado_operacional USING btree (criado_em DESC);


--
-- Name: idx_import_legado_usuario_destino; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_import_legado_usuario_destino ON public.importacoes_legado_operacional USING btree (usuario_destino_id);


--
-- Name: idx_kb_documento_etapas_etapa; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_kb_documento_etapas_etapa ON public.kb_documento_etapas USING btree (etapa);


--
-- Name: idx_kb_documentos_acesso; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_kb_documentos_acesso ON public.kb_documentos USING btree (nivel_acesso);


--
-- Name: idx_kb_documentos_categoria; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_kb_documentos_categoria ON public.kb_documentos USING btree (categoria);


--
-- Name: idx_kb_documentos_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_kb_documentos_status ON public.kb_documentos USING btree (status);


--
-- Name: idx_kb_versoes_documento_data; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_kb_versoes_documento_data ON public.kb_documento_versoes USING btree (documento_id, publicado_em DESC);


--
-- Name: idx_lote_cq_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_lote_cq_status ON public.lotes_controle_qualidade USING btree (status);


--
-- Name: idx_lote_itens_resultado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_lote_itens_resultado ON public.lotes_controle_qualidade_itens USING btree (lote_id, resultado);


--
-- Name: idx_mapeamentos_importacao_criado_em; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mapeamentos_importacao_criado_em ON public.mapeamentos_importacao USING btree (criado_em DESC);


--
-- Name: idx_metas_producao_ativa; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_metas_producao_ativa ON public.metas_producao USING btree (ativa) WHERE (ativa = true);


--
-- Name: idx_metas_producao_etapa; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_metas_producao_etapa ON public.metas_producao USING btree (etapa_id);


--
-- Name: idx_movimentacoes_etapa_tipo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_movimentacoes_etapa_tipo ON public.movimentacoes_armario USING btree (etapa, tipo_movimentacao);


--
-- Name: idx_movimentacoes_repositorio_data; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_movimentacoes_repositorio_data ON public.movimentacoes_armario USING btree (repositorio_id, data_movimentacao DESC);


--
-- Name: idx_producao_repositorio_etapa_data; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_producao_repositorio_etapa_data ON public.producao_repositorio USING btree (repositorio_id, etapa, data_producao DESC);


--
-- Name: idx_receb_apenso_principal; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_receb_apenso_principal ON public.recebimento_apensos USING btree (processo_principal_id);


--
-- Name: idx_receb_apenso_protocolo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_receb_apenso_protocolo ON public.recebimento_apensos USING btree (protocolo);


--
-- Name: idx_receb_apvol_apenso; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_receb_apvol_apenso ON public.recebimento_apenso_volumes USING btree (apenso_id);


--
-- Name: idx_receb_apvol_apenso_numero; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_receb_apvol_apenso_numero ON public.recebimento_apenso_volumes USING btree (apenso_id, numero_volume);


--
-- Name: idx_receb_doc_origem; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_receb_doc_origem ON public.recebimento_documentos USING btree (origem);


--
-- Name: idx_receb_doc_repositorio_data; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_receb_doc_repositorio_data ON public.recebimento_documentos USING btree (repositorio_id, criado_em DESC);


--
-- Name: idx_receb_proc_avulsos; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_receb_proc_avulsos ON public.recebimento_processos USING btree (criado_em DESC) WHERE (repositorio_id IS NULL);


--
-- Name: idx_receb_proc_classificacao; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_receb_proc_classificacao ON public.recebimento_processos USING btree (classificacao_id);


--
-- Name: idx_receb_proc_criado_em; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_receb_proc_criado_em ON public.recebimento_processos USING btree (criado_em DESC);


--
-- Name: idx_receb_proc_interessado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_receb_proc_interessado ON public.recebimento_processos USING btree (interessado);


--
-- Name: idx_receb_proc_protocolo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_receb_proc_protocolo ON public.recebimento_processos USING btree (protocolo);


--
-- Name: idx_receb_proc_repositorio; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_receb_proc_repositorio ON public.recebimento_processos USING btree (repositorio_id);


--
-- Name: idx_receb_proc_setor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_receb_proc_setor ON public.recebimento_processos USING btree (setor_id);


--
-- Name: idx_receb_vol_processo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_receb_vol_processo ON public.recebimento_volumes USING btree (processo_id);


--
-- Name: idx_receb_vol_processo_numero; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_receb_vol_processo_numero ON public.recebimento_volumes USING btree (processo_id, numero_volume);


--
-- Name: idx_refresh_tokens_token; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_refresh_tokens_token ON public.refresh_tokens USING btree (token_hash);


--
-- Name: idx_refresh_tokens_usuario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_refresh_tokens_usuario ON public.refresh_tokens USING btree (usuario_id);


--
-- Name: idx_refresh_tokens_validos; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_refresh_tokens_validos ON public.refresh_tokens USING btree (usuario_id, revogado) WHERE (revogado = false);


--
-- Name: idx_registros_ativos; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_registros_ativos ON public.registros_producao USING btree (processo_id, etapa_id, data_producao) WHERE (cancelado = false);


--
-- Name: idx_registros_colaborador; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_registros_colaborador ON public.registros_producao USING btree (colaborador_id);


--
-- Name: idx_registros_data_producao; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_registros_data_producao ON public.registros_producao USING btree (data_producao);


--
-- Name: idx_registros_data_registro; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_registros_data_registro ON public.registros_producao USING btree (data_registro);


--
-- Name: idx_registros_etapa; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_registros_etapa ON public.registros_producao USING btree (etapa_id);


--
-- Name: idx_registros_importacao; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_registros_importacao ON public.registros_producao USING btree (importacao_id);


--
-- Name: idx_registros_processo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_registros_processo ON public.registros_producao USING btree (processo_id);


--
-- Name: idx_registros_relatorio; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_registros_relatorio ON public.registros_producao USING btree (colaborador_id, etapa_id, data_producao) WHERE (cancelado = false);


--
-- Name: idx_registros_volume; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_registros_volume ON public.registros_producao USING btree (volume_id) WHERE (volume_id IS NOT NULL);


--
-- Name: idx_relatorios_tipo_data; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_relatorios_tipo_data ON public.relatorios_operacionais USING btree (tipo, gerado_em DESC);


--
-- Name: idx_repositorios_armario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_repositorios_armario ON public.repositorios USING btree (localizacao_fisica_armario_id);


--
-- Name: idx_repositorios_etapa; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_repositorios_etapa ON public.repositorios USING btree (etapa_atual);


--
-- Name: idx_repositorios_seadesk_confirmado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_repositorios_seadesk_confirmado ON public.repositorios USING btree (seadesk_confirmado_em) WHERE (seadesk_confirmado_em IS NOT NULL);


--
-- Name: idx_repositorios_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_repositorios_status ON public.repositorios USING btree (status_atual);


--
-- Name: idx_setor_receb_nome_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_setor_receb_nome_unique ON public.setores_recebimento USING btree (lower(TRIM(BOTH FROM nome))) WHERE (ativo = true);


--
-- Name: idx_usuarios_ativos; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_usuarios_ativos ON public.usuarios USING btree (ativo) WHERE (ativo = true);


--
-- Name: idx_usuarios_coordenadoria; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_usuarios_coordenadoria ON public.usuarios USING btree (coordenadoria_id);


--
-- Name: idx_usuarios_email; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_usuarios_email ON public.usuarios USING btree (email);


--
-- Name: idx_usuarios_perfil; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_usuarios_perfil ON public.usuarios USING btree (perfil);


--
-- Name: uk_checklists_ativos_por_etapa; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_checklists_ativos_por_etapa ON public.checklists USING btree (repositorio_id, etapa) WHERE (ativo = true);


--
-- Name: armarios audit_armarios; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER audit_armarios AFTER INSERT OR DELETE OR UPDATE ON public.armarios FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_function();


--
-- Name: checklist_itens audit_checklist_itens; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER audit_checklist_itens AFTER INSERT OR DELETE OR UPDATE ON public.checklist_itens FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_function();


--
-- Name: checklists audit_checklists; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER audit_checklists AFTER INSERT OR DELETE OR UPDATE ON public.checklists FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_function();


--
-- Name: classificacoes_recebimento audit_classificacoes_recebimento; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER audit_classificacoes_recebimento AFTER INSERT OR DELETE OR UPDATE ON public.classificacoes_recebimento FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_function();


--
-- Name: colaboradores audit_colaboradores; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER audit_colaboradores AFTER INSERT OR DELETE OR UPDATE ON public.colaboradores FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_function();


--
-- Name: coordenadorias audit_coordenadorias; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER audit_coordenadorias AFTER INSERT OR DELETE OR UPDATE ON public.coordenadorias FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_function();


--
-- Name: etapas audit_etapas; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER audit_etapas AFTER INSERT OR DELETE OR UPDATE ON public.etapas FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_function();


--
-- Name: excecoes_repositorio audit_excecoes_repositorio; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER audit_excecoes_repositorio AFTER INSERT OR DELETE OR UPDATE ON public.excecoes_repositorio FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_function();


--
-- Name: historico_etapas audit_historico_etapas; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER audit_historico_etapas AFTER INSERT OR DELETE OR UPDATE ON public.historico_etapas FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_function();


--
-- Name: importacoes_legado_operacional audit_importacoes_legado_operacional; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER audit_importacoes_legado_operacional AFTER INSERT OR DELETE OR UPDATE ON public.importacoes_legado_operacional FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_function();


--
-- Name: kb_documento_etapas audit_kb_documento_etapas; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER audit_kb_documento_etapas AFTER INSERT OR DELETE OR UPDATE ON public.kb_documento_etapas FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_function();


--
-- Name: kb_documento_versoes audit_kb_documento_versoes; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER audit_kb_documento_versoes AFTER INSERT OR DELETE OR UPDATE ON public.kb_documento_versoes FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_function();


--
-- Name: kb_documentos audit_kb_documentos; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER audit_kb_documentos AFTER INSERT OR DELETE OR UPDATE ON public.kb_documentos FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_function();


--
-- Name: lotes_controle_qualidade audit_lotes_controle_qualidade; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER audit_lotes_controle_qualidade AFTER INSERT OR DELETE OR UPDATE ON public.lotes_controle_qualidade FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_function();


--
-- Name: lotes_controle_qualidade_itens audit_lotes_controle_qualidade_itens; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER audit_lotes_controle_qualidade_itens AFTER INSERT OR DELETE OR UPDATE ON public.lotes_controle_qualidade_itens FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_function();


--
-- Name: movimentacoes_armario audit_movimentacoes_armario; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER audit_movimentacoes_armario AFTER INSERT OR DELETE OR UPDATE ON public.movimentacoes_armario FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_function();


--
-- Name: producao_repositorio audit_producao_repositorio; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER audit_producao_repositorio AFTER INSERT OR DELETE OR UPDATE ON public.producao_repositorio FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_function();


--
-- Name: recebimento_apenso_volumes audit_recebimento_apenso_volumes; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER audit_recebimento_apenso_volumes AFTER INSERT OR DELETE OR UPDATE ON public.recebimento_apenso_volumes FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_function();


--
-- Name: recebimento_apensos audit_recebimento_apensos; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER audit_recebimento_apensos AFTER INSERT OR DELETE OR UPDATE ON public.recebimento_apensos FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_function();


--
-- Name: recebimento_documentos audit_recebimento_documentos; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER audit_recebimento_documentos AFTER INSERT OR DELETE OR UPDATE ON public.recebimento_documentos FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_function();


--
-- Name: recebimento_processos audit_recebimento_processos; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER audit_recebimento_processos AFTER INSERT OR DELETE OR UPDATE ON public.recebimento_processos FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_function();


--
-- Name: recebimento_volumes audit_recebimento_volumes; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER audit_recebimento_volumes AFTER INSERT OR DELETE OR UPDATE ON public.recebimento_volumes FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_function();


--
-- Name: registros_producao audit_registros_producao; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER audit_registros_producao AFTER INSERT OR UPDATE ON public.registros_producao FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_function();


--
-- Name: relatorios_operacionais audit_relatorios_operacionais; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER audit_relatorios_operacionais AFTER INSERT OR DELETE OR UPDATE ON public.relatorios_operacionais FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_function();


--
-- Name: repositorios audit_repositorios; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER audit_repositorios AFTER INSERT OR DELETE OR UPDATE ON public.repositorios FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_function();


--
-- Name: setores_recebimento audit_setores_recebimento; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER audit_setores_recebimento AFTER INSERT OR DELETE OR UPDATE ON public.setores_recebimento FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_function();


--
-- Name: usuarios audit_usuarios; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER audit_usuarios AFTER INSERT OR DELETE OR UPDATE ON public.usuarios FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_function();


--
-- Name: registros_producao prevent_delete_registros_producao; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER prevent_delete_registros_producao BEFORE DELETE ON public.registros_producao FOR EACH ROW EXECUTE FUNCTION public.check_delete_registros_producao();


--
-- Name: lotes_controle_qualidade trigger_aplicar_resultado_cq_em_repositorios; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_aplicar_resultado_cq_em_repositorios AFTER UPDATE ON public.lotes_controle_qualidade FOR EACH ROW EXECUTE FUNCTION public.fn_aplicar_resultado_cq_em_repositorios();


--
-- Name: registros_producao trigger_registros_producao_immutable; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_registros_producao_immutable BEFORE UPDATE ON public.registros_producao FOR EACH ROW EXECUTE FUNCTION public.check_registros_producao_immutable();


--
-- Name: repositorios trigger_validar_avanco_etapa_repositorio; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_validar_avanco_etapa_repositorio BEFORE UPDATE ON public.repositorios FOR EACH ROW EXECUTE FUNCTION public.fn_validar_avanco_etapa_repositorio();


--
-- Name: checklists trigger_validar_conclusao_checklist; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_validar_conclusao_checklist BEFORE UPDATE ON public.checklists FOR EACH ROW EXECUTE FUNCTION public.fn_validar_conclusao_checklist();


--
-- Name: lotes_controle_qualidade trigger_validar_fechamento_lote_cq; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_validar_fechamento_lote_cq BEFORE UPDATE ON public.lotes_controle_qualidade FOR EACH ROW EXECUTE FUNCTION public.fn_validar_fechamento_lote_cq();


--
-- Name: producao_repositorio trigger_validar_producao_com_checklist_ativo; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_validar_producao_com_checklist_ativo BEFORE INSERT ON public.producao_repositorio FOR EACH ROW EXECUTE FUNCTION public.fn_validar_producao_com_checklist_ativo();


--
-- Name: armarios update_armarios_timestamp; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER update_armarios_timestamp BEFORE UPDATE ON public.armarios FOR EACH ROW EXECUTE FUNCTION public.update_timestamp();


--
-- Name: checklist_modelos update_checklist_modelos_timestamp; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER update_checklist_modelos_timestamp BEFORE UPDATE ON public.checklist_modelos FOR EACH ROW EXECUTE FUNCTION public.update_timestamp();


--
-- Name: checklists update_checklists_timestamp; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER update_checklists_timestamp BEFORE UPDATE ON public.checklists FOR EACH ROW EXECUTE FUNCTION public.update_timestamp();


--
-- Name: kb_documentos update_kb_documentos_timestamp; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER update_kb_documentos_timestamp BEFORE UPDATE ON public.kb_documentos FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: repositorios update_repositorios_timestamp; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER update_repositorios_timestamp BEFORE UPDATE ON public.repositorios FOR EACH ROW EXECUTE FUNCTION public.update_timestamp();


--
-- Name: usuarios update_usuarios_timestamp; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER update_usuarios_timestamp BEFORE UPDATE ON public.usuarios FOR EACH ROW EXECUTE FUNCTION public.update_timestamp();


--
-- Name: auditoria fk_auditoria_colaborador; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auditoria
    ADD CONSTRAINT fk_auditoria_colaborador FOREIGN KEY (colaborador_id) REFERENCES public.colaboradores(id) ON DELETE SET NULL;


--
-- Name: checklist_itens fk_checklist_item_checklist; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checklist_itens
    ADD CONSTRAINT fk_checklist_item_checklist FOREIGN KEY (checklist_id) REFERENCES public.checklists(id) ON DELETE CASCADE;


--
-- Name: checklist_itens fk_checklist_item_modelo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checklist_itens
    ADD CONSTRAINT fk_checklist_item_modelo FOREIGN KEY (modelo_id) REFERENCES public.checklist_modelos(id) ON DELETE RESTRICT;


--
-- Name: checklist_itens fk_checklist_item_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checklist_itens
    ADD CONSTRAINT fk_checklist_item_usuario FOREIGN KEY (responsavel_id) REFERENCES public.usuarios(id) ON DELETE RESTRICT;


--
-- Name: checklists fk_checklists_repositorio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checklists
    ADD CONSTRAINT fk_checklists_repositorio FOREIGN KEY (repositorio_id) REFERENCES public.repositorios(id_repositorio_recorda) ON DELETE CASCADE;


--
-- Name: checklists fk_checklists_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checklists
    ADD CONSTRAINT fk_checklists_usuario FOREIGN KEY (responsavel_id) REFERENCES public.usuarios(id) ON DELETE RESTRICT;


--
-- Name: classificacoes_recebimento fk_classif_receb_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classificacoes_recebimento
    ADD CONSTRAINT fk_classif_receb_usuario FOREIGN KEY (criado_por) REFERENCES public.usuarios(id) ON DELETE RESTRICT;


--
-- Name: colaboradores fk_colaboradores_coordenadoria; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.colaboradores
    ADD CONSTRAINT fk_colaboradores_coordenadoria FOREIGN KEY (coordenadoria_id) REFERENCES public.coordenadorias(id) ON DELETE RESTRICT;


--
-- Name: excecoes_repositorio fk_excecao_repositorio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.excecoes_repositorio
    ADD CONSTRAINT fk_excecao_repositorio FOREIGN KEY (repositorio_id) REFERENCES public.repositorios(id_repositorio_recorda) ON DELETE CASCADE;


--
-- Name: excecoes_repositorio fk_excecao_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.excecoes_repositorio
    ADD CONSTRAINT fk_excecao_usuario FOREIGN KEY (responsavel_id) REFERENCES public.usuarios(id) ON DELETE RESTRICT;


--
-- Name: historico_etapas fk_historico_repositorio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historico_etapas
    ADD CONSTRAINT fk_historico_repositorio FOREIGN KEY (repositorio_id) REFERENCES public.repositorios(id_repositorio_recorda) ON DELETE CASCADE;


--
-- Name: historico_etapas fk_historico_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historico_etapas
    ADD CONSTRAINT fk_historico_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE SET NULL;


--
-- Name: importacoes_legado_operacional fk_import_legado_executado_por; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.importacoes_legado_operacional
    ADD CONSTRAINT fk_import_legado_executado_por FOREIGN KEY (executado_por) REFERENCES public.usuarios(id) ON DELETE RESTRICT;


--
-- Name: importacoes_legado_operacional fk_import_legado_usuario_destino; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.importacoes_legado_operacional
    ADD CONSTRAINT fk_import_legado_usuario_destino FOREIGN KEY (usuario_destino_id) REFERENCES public.usuarios(id) ON DELETE RESTRICT;


--
-- Name: kb_documento_etapas fk_kb_documento_etapas_documento; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kb_documento_etapas
    ADD CONSTRAINT fk_kb_documento_etapas_documento FOREIGN KEY (documento_id) REFERENCES public.kb_documentos(id) ON DELETE CASCADE;


--
-- Name: kb_documentos fk_kb_documentos_criado_por; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kb_documentos
    ADD CONSTRAINT fk_kb_documentos_criado_por FOREIGN KEY (criado_por) REFERENCES public.usuarios(id) ON DELETE RESTRICT;


--
-- Name: kb_documentos fk_kb_documentos_versao_atual; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kb_documentos
    ADD CONSTRAINT fk_kb_documentos_versao_atual FOREIGN KEY (versao_atual_id) REFERENCES public.kb_documento_versoes(id) ON DELETE SET NULL;


--
-- Name: kb_documento_versoes fk_kb_versoes_documento; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kb_documento_versoes
    ADD CONSTRAINT fk_kb_versoes_documento FOREIGN KEY (documento_id) REFERENCES public.kb_documentos(id) ON DELETE CASCADE;


--
-- Name: kb_documento_versoes fk_kb_versoes_publicado_por; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kb_documento_versoes
    ADD CONSTRAINT fk_kb_versoes_publicado_por FOREIGN KEY (publicado_por) REFERENCES public.usuarios(id) ON DELETE RESTRICT;


--
-- Name: lotes_controle_qualidade fk_lote_cq_auditor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lotes_controle_qualidade
    ADD CONSTRAINT fk_lote_cq_auditor FOREIGN KEY (auditor_id) REFERENCES public.usuarios(id) ON DELETE RESTRICT;


--
-- Name: lotes_controle_qualidade_itens fk_lote_item_auditor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lotes_controle_qualidade_itens
    ADD CONSTRAINT fk_lote_item_auditor FOREIGN KEY (auditor_id) REFERENCES public.usuarios(id) ON DELETE SET NULL;


--
-- Name: lotes_controle_qualidade_itens fk_lote_item_lote; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lotes_controle_qualidade_itens
    ADD CONSTRAINT fk_lote_item_lote FOREIGN KEY (lote_id) REFERENCES public.lotes_controle_qualidade(id) ON DELETE CASCADE;


--
-- Name: lotes_controle_qualidade_itens fk_lote_item_repositorio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lotes_controle_qualidade_itens
    ADD CONSTRAINT fk_lote_item_repositorio FOREIGN KEY (repositorio_id) REFERENCES public.repositorios(id_repositorio_recorda) ON DELETE RESTRICT;


--
-- Name: metas_producao fk_metas_producao_etapa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.metas_producao
    ADD CONSTRAINT fk_metas_producao_etapa FOREIGN KEY (etapa_id) REFERENCES public.etapas(id) ON DELETE RESTRICT;


--
-- Name: movimentacoes_armario fk_movimentacao_armario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movimentacoes_armario
    ADD CONSTRAINT fk_movimentacao_armario FOREIGN KEY (armario_id) REFERENCES public.armarios(id) ON DELETE RESTRICT;


--
-- Name: movimentacoes_armario fk_movimentacao_repositorio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movimentacoes_armario
    ADD CONSTRAINT fk_movimentacao_repositorio FOREIGN KEY (repositorio_id) REFERENCES public.repositorios(id_repositorio_recorda) ON DELETE CASCADE;


--
-- Name: movimentacoes_armario fk_movimentacao_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movimentacoes_armario
    ADD CONSTRAINT fk_movimentacao_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE RESTRICT;


--
-- Name: producao_repositorio fk_producao_checklist; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.producao_repositorio
    ADD CONSTRAINT fk_producao_checklist FOREIGN KEY (checklist_id) REFERENCES public.checklists(id) ON DELETE RESTRICT;


--
-- Name: producao_repositorio fk_producao_repositorio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.producao_repositorio
    ADD CONSTRAINT fk_producao_repositorio FOREIGN KEY (repositorio_id) REFERENCES public.repositorios(id_repositorio_recorda) ON DELETE CASCADE;


--
-- Name: producao_repositorio fk_producao_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.producao_repositorio
    ADD CONSTRAINT fk_producao_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE RESTRICT;


--
-- Name: recebimento_apensos fk_receb_apenso_principal; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recebimento_apensos
    ADD CONSTRAINT fk_receb_apenso_principal FOREIGN KEY (processo_principal_id) REFERENCES public.recebimento_processos(id) ON DELETE CASCADE;


--
-- Name: recebimento_apensos fk_receb_apenso_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recebimento_apensos
    ADD CONSTRAINT fk_receb_apenso_usuario FOREIGN KEY (criado_por) REFERENCES public.usuarios(id) ON DELETE RESTRICT;


--
-- Name: recebimento_apenso_volumes fk_receb_apvol_apenso; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recebimento_apenso_volumes
    ADD CONSTRAINT fk_receb_apvol_apenso FOREIGN KEY (apenso_id) REFERENCES public.recebimento_apensos(id) ON DELETE CASCADE;


--
-- Name: recebimento_apenso_volumes fk_receb_apvol_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recebimento_apenso_volumes
    ADD CONSTRAINT fk_receb_apvol_usuario FOREIGN KEY (criado_por) REFERENCES public.usuarios(id) ON DELETE RESTRICT;


--
-- Name: recebimento_documentos fk_receb_doc_repositorio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recebimento_documentos
    ADD CONSTRAINT fk_receb_doc_repositorio FOREIGN KEY (repositorio_id) REFERENCES public.repositorios(id_repositorio_recorda) ON DELETE CASCADE;


--
-- Name: recebimento_documentos fk_receb_doc_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recebimento_documentos
    ADD CONSTRAINT fk_receb_doc_usuario FOREIGN KEY (criado_por) REFERENCES public.usuarios(id) ON DELETE RESTRICT;


--
-- Name: recebimento_processos fk_receb_proc_classificacao; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recebimento_processos
    ADD CONSTRAINT fk_receb_proc_classificacao FOREIGN KEY (classificacao_id) REFERENCES public.classificacoes_recebimento(id) ON DELETE SET NULL;


--
-- Name: recebimento_processos fk_receb_proc_repositorio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recebimento_processos
    ADD CONSTRAINT fk_receb_proc_repositorio FOREIGN KEY (repositorio_id) REFERENCES public.repositorios(id_repositorio_recorda) ON DELETE CASCADE;


--
-- Name: recebimento_processos fk_receb_proc_setor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recebimento_processos
    ADD CONSTRAINT fk_receb_proc_setor FOREIGN KEY (setor_id) REFERENCES public.setores_recebimento(id) ON DELETE SET NULL;


--
-- Name: recebimento_processos fk_receb_proc_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recebimento_processos
    ADD CONSTRAINT fk_receb_proc_usuario FOREIGN KEY (criado_por) REFERENCES public.usuarios(id) ON DELETE RESTRICT;


--
-- Name: recebimento_volumes fk_receb_vol_processo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recebimento_volumes
    ADD CONSTRAINT fk_receb_vol_processo FOREIGN KEY (processo_id) REFERENCES public.recebimento_processos(id) ON DELETE CASCADE;


--
-- Name: recebimento_volumes fk_receb_vol_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recebimento_volumes
    ADD CONSTRAINT fk_receb_vol_usuario FOREIGN KEY (criado_por) REFERENCES public.usuarios(id) ON DELETE RESTRICT;


--
-- Name: registros_producao fk_registros_cancelado_por; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registros_producao
    ADD CONSTRAINT fk_registros_cancelado_por FOREIGN KEY (cancelado_por) REFERENCES public.colaboradores(id) ON DELETE RESTRICT;


--
-- Name: registros_producao fk_registros_colaborador; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registros_producao
    ADD CONSTRAINT fk_registros_colaborador FOREIGN KEY (colaborador_id) REFERENCES public.colaboradores(id) ON DELETE RESTRICT;


--
-- Name: registros_producao fk_registros_etapa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registros_producao
    ADD CONSTRAINT fk_registros_etapa FOREIGN KEY (etapa_id) REFERENCES public.etapas(id) ON DELETE RESTRICT;


--
-- Name: relatorios_operacionais fk_relatorio_gerado_por; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.relatorios_operacionais
    ADD CONSTRAINT fk_relatorio_gerado_por FOREIGN KEY (gerado_por) REFERENCES public.usuarios(id) ON DELETE RESTRICT;


--
-- Name: relatorios_operacionais fk_relatorio_lote; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.relatorios_operacionais
    ADD CONSTRAINT fk_relatorio_lote FOREIGN KEY (lote_id) REFERENCES public.lotes_controle_qualidade(id) ON DELETE SET NULL;


--
-- Name: relatorios_operacionais fk_relatorio_repositorio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.relatorios_operacionais
    ADD CONSTRAINT fk_relatorio_repositorio FOREIGN KEY (repositorio_id) REFERENCES public.repositorios(id_repositorio_recorda) ON DELETE SET NULL;


--
-- Name: repositorios fk_repositorio_armario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.repositorios
    ADD CONSTRAINT fk_repositorio_armario FOREIGN KEY (localizacao_fisica_armario_id) REFERENCES public.armarios(id) ON DELETE RESTRICT;


--
-- Name: setores_recebimento fk_setor_receb_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.setores_recebimento
    ADD CONSTRAINT fk_setor_receb_usuario FOREIGN KEY (criado_por) REFERENCES public.usuarios(id) ON DELETE RESTRICT;


--
-- Name: refresh_tokens refresh_tokens_usuario_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE CASCADE;


--
-- Name: repositorios repositorios_seadesk_confirmado_por_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.repositorios
    ADD CONSTRAINT repositorios_seadesk_confirmado_por_fkey FOREIGN KEY (seadesk_confirmado_por) REFERENCES public.usuarios(id);


--
-- Name: usuarios usuarios_coordenadoria_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_coordenadoria_id_fkey FOREIGN KEY (coordenadoria_id) REFERENCES public.coordenadorias(id) ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--

\unrestrict tZvBcePdEsgj9BjUozxsOhSBKLAqS7UovDYQmoViuw0ZXaWjObTTsTAR4TCoMdO
