#!/usr/bin/env node
/**
 * Database Migration Consolidation Script
 *
 * Connects to the database, dumps the current schema + seed data,
 * and archives old migration files.
 *
 * Usage:
 *   node db/scripts/consolidate.mjs
 *
 * Prerequisites:
 *   - PostgreSQL running with all migrations applied
 *   - pg_dump available in PATH
 *   - Environment variables: DB_HOST, DB_PORT, DB_USER, DB_PASSWORD, DB_NAME
 */

import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const dbDir = path.resolve(__dirname, '..');
const migrationsDir = path.join(dbDir, 'migrations');
const archiveDir = path.join(migrationsDir, 'archive');
const baselineDir = path.join(dbDir, 'baseline');

const DB_USER = process.env.DB_USER || 'recorda';
const DB_NAME = process.env.DB_NAME || 'recorda';
const CONTAINER = process.env.PG_CONTAINER || 'recorda-postgres';

function run(cmd) {
  return execSync(cmd, { encoding: 'utf-8' }).trim();
}

function pgDump(args) {
  return run(`docker exec ${CONTAINER} pg_dump -U ${DB_USER} -d ${DB_NAME} ${args}`);
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

// ---------------------------------------------------------------------------
// 1. Dump schema (no data, no owner, no privileges)
// ---------------------------------------------------------------------------
console.log('Dumping schema...');
ensureDir(baselineDir);

const schemaFile = path.join(baselineDir, '000_baseline_schema.sql');
const schemaSql = pgDump('--schema-only --no-owner --no-privileges --no-comments');

const schemaHeader = [
  '-- ==========================================================================',
  '-- Baseline Schema — auto-generated by db/scripts/consolidate.mjs',
  `-- Generated: ${new Date().toISOString()}`,
  `-- Source: container ${CONTAINER} / ${DB_NAME}`,
  '-- ==========================================================================',
  '',
].join('\n');

fs.writeFileSync(schemaFile, schemaHeader + schemaSql + '\n');
console.log(`  → ${path.relative(dbDir, schemaFile)}`);

// ---------------------------------------------------------------------------
// 2. Dump seed data (checklist_modelos, classificacoes_recebimento, schema_migrations)
// ---------------------------------------------------------------------------
console.log('Dumping seed data...');

const seedTables = [
  'checklist_modelos',
  'classificacoes_recebimento',
  'schema_migrations',
];

const dataFile = path.join(baselineDir, '000_baseline_data.sql');
let dataSql = [
  '-- ==========================================================================',
  '-- Baseline Seed Data — auto-generated by db/scripts/consolidate.mjs',
  `-- Generated: ${new Date().toISOString()}`,
  '-- ==========================================================================',
  '',
].join('\n');

for (const table of seedTables) {
  try {
    const tableDump = pgDump(`--data-only --table=${table} --no-owner --inserts`);
    if (tableDump.trim()) {
      dataSql += `\n-- ${table}\n${tableDump}\n`;
    }
  } catch {
    console.log(`  ⚠ Table ${table} not found or empty, skipping.`);
  }
}

fs.writeFileSync(dataFile, dataSql);
console.log(`  → ${path.relative(dbDir, dataFile)}`);

// ---------------------------------------------------------------------------
// 3. Archive old migrations
// ---------------------------------------------------------------------------
console.log('Archiving old migrations...');
ensureDir(archiveDir);

const migrationFiles = fs.readdirSync(migrationsDir)
  .filter(f => f.endsWith('.sql'))
  .sort();

let archived = 0;
for (const file of migrationFiles) {
  const src = path.join(migrationsDir, file);
  const dst = path.join(archiveDir, file);
  fs.renameSync(src, dst);
  archived++;
}

console.log(`  → ${archived} migrations archived to migrations/archive/`);

// ---------------------------------------------------------------------------
// Done
// ---------------------------------------------------------------------------
console.log('\n✅ Consolidation complete.');
console.log('   New migrations should start at 051_*.sql');
console.log('   The baseline files are in db/baseline/');
console.log('   Archived migrations are in db/migrations/archive/');
